#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the vxlan module
"""


class VxlanArgs(object):  # pylint: disable=R0903
    """The arg spec for the vxlan module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'interface': {'elements': 'dict',
                                      'options': {'name': {'required': True,
                                                           'type': 'str'},
                                                  'source-ip': {'type': 'str'},
                                                  'vni': {'elements': 'dict',
                                                          'options': {'vlan-id': {'required': True,
                                                                                  'type': 'int'},
                                                                      'vni-id': {'required': True,
                                                                                 'type': 'int'}},
                                                          'type': 'list'},
                                                  'vtep-mac': {'type': 'str'}},
                                      'required_by': {'vtep-mac': ['source-ip']},
                                      'type': 'list'},
                        'vni-map': {'elements': 'dict',
                                    'options': {'name': {'required': True,
                                                         'type': 'str'},
                                                'vni-id': {'type': 'int'}},
                                    'type': 'list'},
                        'vxlan-profile': {'type': 'bool'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
