#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the qos_buffer module
"""


class Qos_bufferArgs(object):  # pylint: disable=R0903
    """The arg spec for the qos_buffer module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'buffer-mgmt': {'type': 'bool'},
                        'buffer-profile-egress': {'elements': 'dict',
                                                  'mutually_exclusive': [['dynamic-threshold',
                                                                          'static-threshold']],
                                                  'options': {'buffer-pool': {'choices': ['egress_default_lossy_pool',
                                                                                          'egress_lossless_pool'],
                                                                              'type': 'str'},
                                                              'dynamic-threshold': {'type': 'int'},
                                                              'name': {'required': True,
                                                                       'type': 'str'},
                                                              'size': {'type': 'int'},
                                                              'static-threshold': {'type': 'int'}},
                                                  'type': 'list'},
                        'buffer-profile-ingress': {'elements': 'dict',
                                                   'mutually_exclusive': [['dynamic-threshold',
                                                                           'static-threshold']],
                                                   'options': {'buffer-pool': {'choices': ['ingress_default_lossy_pool',
                                                                                           'ingress_lossless_pool'],
                                                                               'type': 'str'},
                                                               'dynamic-threshold': {'type': 'int'},
                                                               'headroom': {'type': 'int'},
                                                               'name': {'required': True,
                                                                        'type': 'str'},
                                                               'size': {'type': 'int'},
                                                               'static-threshold': {'type': 'int'},
                                                               'xon': {'type': 'int'}},
                                                   'type': 'list'},
                        'interface': {'elements': 'dict',
                                      'options': {'buffer-queue-profile': {'elements': 'dict',
                                                                           'options': {'name': {'required': True,
                                                                                                'type': 'str'},
                                                                                       'queue': {'required': True,
                                                                                                 'type': 'int'}},
                                                                           'type': 'list'},
                                                  'name': {'required': True,
                                                           'type': 'str'},
                                                  'priority-flow-control': {'elements': 'dict',
                                                                            'options': {'group': {'required': True,
                                                                                                  'type': 'int'},
                                                                                        'mode': {'choices': ['enable',
                                                                                                             'disable'],
                                                                                                 'required': True,
                                                                                                 'type': 'str'}},
                                                                            'type': 'list'},
                                                  'priority-group-profile': {'elements': 'dict',
                                                                             'options': {'group': {'required': True,
                                                                                                   'type': 'int'},
                                                                                         'name': {'required': True,
                                                                                                  'type': 'str'}},
                                                                             'type': 'list'}},
                                      'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
