#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the tacacs module
"""


class TacacsArgs(object):  # pylint: disable=R0903
    """The arg spec for the tacacs module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'global': {'options': {'auth-type': {'choices': ['pap',
                                                                         'chap',
                                                                         'login'],
                                                             'type': 'str'},
                                               'encrypted-passkey': {'type': 'str'},
                                               'timeout': {'type': 'str'}},
                                   'type': 'dict'},
                        'server': {'elements': 'dict',
                                   'options': {'auth-type': {'choices': ['pap',
                                                                         'chap',
                                                                         'login'],
                                                             'type': 'str'},
                                               'encrypted-passkey': {'type': 'str'},
                                               'ip-addr': {'required': True,
                                                           'type': 'str'},
                                               'port': {'type': 'int'},
                                               'priority': {'type': 'int'},
                                               'timeout': {'type': 'str'},
                                               'vrf': {'choices': ['mgmt'],
                                                       'type': 'str'}},
                                   'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
