#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the stp module
"""


class StpArgs(object):  # pylint: disable=R0903
    """The arg spec for the stp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'global': {'options': {'ageing-time': {'type': 'int'},
                                               'forward-delay': {'type': 'int'},
                                               'hello-time': {'type': 'int'},
                                               'max-age': {'type': 'int'},
                                               'max-hops': {'type': 'int'},
                                               'priority': {'type': 'int'},
                                               'protocol': {'choices': ['rstp'],
                                                            'type': 'str'}},
                                   'type': 'dict'},
                        'interface': {'elements': 'dict',
                                      'options': {'admin-edge': {'type': 'bool'},
                                                  'bpdu-guard': {'type': 'bool'},
                                                  'cost': {'type': 'int'},
                                                  'enable': {'type': 'bool'},
                                                  'name': {'required': True,
                                                           'type': 'str'},
                                                  'network-state': {'type': 'bool'},
                                                  'p2p': {'choices': ['auto',
                                                                      'enable'],
                                                          'type': 'str'}},
                                      'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
