#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the dot1x module
"""


class Dot1xArgs(object):  # pylint: disable=R0903
    """The arg spec for the dot1x module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'interface': {'elements': 'dict',
                                      'options': {'auth-mode': {'choices': ['multi-host',
                                                                            'single-host'],
                                                                'type': 'str'},
                                                  'enable': {'type': 'bool'},
                                                  'mab-backoff-timer': {'type': 'int'},
                                                  'mab-enable': {'type': 'bool'},
                                                  'max-clients': {'type': 'int'},
                                                  'name': {'required': True,
                                                           'type': 'str'},
                                                  'reauth-timer': {'type': 'int'}},
                                      'type': 'list'},
                        'radius': {'options': {'server': {'elements': 'dict',
                                                          'options': {'encrypted-passkey': {'type': 'str'},
                                                                      'ip-addr': {'type': 'str'},
                                                                      'port': {'type': 'int'},
                                                                      'type': {'choices': ['primary',
                                                                                           'secondary'],
                                                                               'required': True,
                                                                               'type': 'str'},
                                                                      'vrf': {'type': 'str'}},
                                                          'type': 'list'},
                                               'vsa-vlan': {'elements': 'dict',
                                                            'options': {'vlan': {'type': 'int'},
                                                                        'vsa-description': {'required': True,
                                                                                            'type': 'str'}},
                                                            'type': 'list'}},
                                   'type': 'dict'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
