#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the poe module
"""


class PoeArgs(object):  # pylint: disable=R0903
    """The arg spec for the poe module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'global': {'options': {'disable': {'type': 'bool'},
                                               'guard-band': {'type': 'str'},
                                               'power-management': {'choices': ['dynamic-with-priority',
                                                                                'dynamic-without-priority',
                                                                                'static-with-priority',
                                                                                'static-without-priority'],
                                                                    'type': 'str'}},
                                   'type': 'dict'},
                        'interface': {'elements': 'dict',
                                      'options': {'auto-reset-timer': {'type': 'int'},
                                                  'detection-type': {'choices': ['two-point-dot3af',
                                                                                 'two-point-dot3af-legacy',
                                                                                 'four-point-dot3af',
                                                                                 'four-point-dot3af-legacy',
                                                                                 'legacy-only'],
                                                                     'type': 'str'},
                                                  'enable': {'type': 'bool'},
                                                  'name': {'required': True,
                                                           'type': 'str'},
                                                  'power-threshold': {'choices': ['class-based',
                                                                                  'power-up-based',
                                                                                  'user-defined'],
                                                                      'type': 'str'},
                                                  'power-up-mode': {'choices': ['dot3af',
                                                                                'pre-dot3at',
                                                                                'dot3at',
                                                                                'pre-dot3bt',
                                                                                'dot3bt-type3',
                                                                                'dot3bt-type4',
                                                                                'high-inrush'],
                                                                    'type': 'str'},
                                                  'power-via-mdi': {'type': 'bool'},
                                                  'priority': {'choices': ['critical',
                                                                           'high',
                                                                           'medium',
                                                                           'low'],
                                                               'type': 'str'},
                                                  'reset-mode': {'choices': ['auto',
                                                                             'manual'],
                                                                 'type': 'str'},
                                                  'user-defined-threshold': {'type': 'str'}},
                                      'required_if': [['power-threshold',
                                                       'user-defined',
                                                       ['user-defined-threshold']],
                                                      ['reset-mode',
                                                       'auto',
                                                       ['auto-reset-timer']]],
                                      'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
