#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the lldp module
"""


class LldpArgs(object):  # pylint: disable=R0903
    """The arg spec for the lldp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'global': {'options': {'enable': {'type': 'bool'},
                                               'hello-interval': {'type': 'int'},
                                               'system-description': {'type': 'str'},
                                               'system-name': {'type': 'str'},
                                               'tlv-select': {'options': {'management-address': {'type': 'bool'},
                                                                          'system-capabilities': {'type': 'bool'}},
                                                              'type': 'dict'}},
                                   'type': 'dict'},
                        'interface': {'elements': 'dict',
                                      'options': {'enable': {'type': 'bool'},
                                                  'med': {'options': {'network-policy': {'options': {'application': {'choices': ['voice',
                                                                                                                                 'voice-signaling',
                                                                                                                                 'guest-voice',
                                                                                                                                 'guest-voice-signaling',
                                                                                                                                 'softphone-voice',
                                                                                                                                 'video-conferencing',
                                                                                                                                 'streaming-video',
                                                                                                                                 'video-signaling'],
                                                                                                                     'type': 'str'},
                                                                                                     'dscp': {'type': 'int'},
                                                                                                     'priority': {'type': 'int'},
                                                                                                     'tagged': {'type': 'bool'},
                                                                                                     'vlan': {'type': 'int'}},
                                                                                         'type': 'dict'}},
                                                          'type': 'dict'},
                                                  'name': {'required': True,
                                                           'type': 'str'}},
                                      'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
