#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the interface module
"""


class InterfaceArgs(object):  # pylint: disable=R0903
    """The arg spec for the interface module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'interface': {'elements': 'dict',
                                      'options': {'advertise-speed': {'type': 'str'},
                                                  'advertise-type': {'type': 'str'},
                                                  'channel-group': {'type': 'int'},
                                                  'description': {'type': 'str'},
                                                  'enabled': {'type': 'bool'},
                                                  'fec': {'choices': ['FC',
                                                                      'RS',
                                                                      'none'],
                                                          'type': 'str'},
                                                  'mtu': {'type': 'int'},
                                                  'name': {'required': True,
                                                           'type': 'str'},
                                                  'speed': {'type': 'str'},
                                                  'storm-control': {'elements': 'dict',
                                                                    'options': {'rate': {'type': 'int'},
                                                                                'type': {'choices': ['broadcast',
                                                                                                     'unknown-multicast',
                                                                                                     'unknown-unicast'],
                                                                                         'type': 'str'}},
                                                                    'type': 'list'},
                                                  'tpid': {'choices': ['0x8100',
                                                                       '0x88a8',
                                                                       '0x9100',
                                                                       '0x9200'],
                                                           'type': 'str'},
                                                  'type': {'type': 'str'}},
                                      'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
