#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the snmp module
"""


class SnmpArgs(object):  # pylint: disable=R0903
    """The arg spec for the snmp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'agent-address': {'elements': 'dict',
                                          'options': {'ip-addr': {'required': True,
                                                                  'type': 'str'},
                                                      'port': {'type': 'int'},
                                                      'vrf': {'type': 'str'}},
                                          'type': 'list'},
                        'community': {'elements': 'dict',
                                      'options': {'access': {'choices': ['read-only',
                                                                         'read-write'],
                                                             'type': 'str'},
                                                  'name': {'required': True,
                                                           'type': 'str'}},
                                      'type': 'list'},
                        'snmp-server': {'options': {'contact': {'type': 'str'},
                                                    'location': {'type': 'str'}},
                                        'type': 'dict'},
                        'trap-host': {'elements': 'dict',
                                      'options': {'community': {'type': 'str'},
                                                  'ip-addr': {'required': True,
                                                              'type': 'str'},
                                                  'port': {'type': 'int'},
                                                  'version': {'required': True,
                                                              'type': 'int'},
                                                  'vrf': {'type': 'str'}},
                                      'type': 'list'},
                        'user': {'elements': 'dict',
                                 'options': {'access': {'choices': ['read-only',
                                                                    'read-write'],
                                                        'type': 'str'},
                                             'auth-algorithm': {'choices': ['sha',
                                                                            'md5'],
                                                                'type': 'str'},
                                             'encrypt-algorithm': {'choices': ['aes',
                                                                               'des'],
                                                                   'type': 'str'},
                                             'encrypted-auth-password': {'type': 'str'},
                                             'encrypted-encrypt-password': {'type': 'str'},
                                             'name': {'required': True,
                                                      'type': 'str'},
                                             'user-type': {'choices': ['noAuthNoPriv',
                                                                       'AuthNoPriv',
                                                                       'Priv'],
                                                           'type': 'str'}},
                                 'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
