#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the mclag module
"""


class MclagArgs(object):  # pylint: disable=R0903
    """The arg spec for the mclag module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'domain': {'elements': 'dict',
                                   'options': {'id': {'required': True,
                                                      'type': 'int'},
                                               'keep-alive': {'type': 'int'},
                                               'peer-ip': {'type': 'str'},
                                               'peer-link': {'type': 'str'},
                                               'session-timeout': {'type': 'int'},
                                               'source-ip': {'type': 'str'},
                                               'system-mac': {'type': 'str'}},
                                   'type': 'list'},
                        'port-channel': {'elements': 'dict',
                                         'options': {'domain': {'type': 'int'},
                                                     'name': {'required': True,
                                                              'type': 'str'}},
                                         'type': 'list'},
                        'vlan': {'elements': 'dict',
                                 'options': {'name': {'required': True,
                                                      'type': 'str'},
                                             'unique-ip': {'type': 'bool'}},
                                 'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
