#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the access_list_mac module
"""


class Access_list_macArgs(object):  # pylint: disable=R0903
    """The arg spec for the access_list_mac module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'access-list': {'elements': 'dict',
                                        'options': {'name': {'required': True,
                                                             'type': 'str'},
                                                    'sequence-numbers': {'elements': 'dict',
                                                                         'mutually_exclusive': [['src-addr-any',
                                                                                                 'src-addr'],
                                                                                                ['src-addr-any',
                                                                                                 'src-mask'],
                                                                                                ['dst-addr-any',
                                                                                                 'dst-addr'],
                                                                                                ['dst-addr-any',
                                                                                                 'dst-mask']],
                                                                         'options': {'action': {'choices': ['deny',
                                                                                                            'permit'],
                                                                                                'type': 'str'},
                                                                                     'dst-addr': {'type': 'str'},
                                                                                     'dst-addr-any': {'type': 'bool'},
                                                                                     'dst-mask': {'type': 'str'},
                                                                                     'ethertype': {'choices': ['0x0800',
                                                                                                               '0x0806',
                                                                                                               '0x86dd',
                                                                                                               '0x8847',
                                                                                                               '0x88cc',
                                                                                                               '0x8915',
                                                                                                               'arp',
                                                                                                               'ip',
                                                                                                               'ipv6'],
                                                                                                   'type': 'str'},
                                                                                     'seq': {'required': True,
                                                                                             'type': 'int'},
                                                                                     'src-addr': {'type': 'str'},
                                                                                     'src-addr-any': {'type': 'bool'},
                                                                                     'src-mask': {'type': 'str'}},
                                                                         'required_together': [['src-addr',
                                                                                                'src-mask'],
                                                                                               ['dst-addr',
                                                                                                'dst-mask']],
                                                                         'type': 'list'}},
                                        'type': 'list'},
                        'interface': {'elements': 'dict',
                                      'options': {'access-group': {'elements': 'dict',
                                                                   'options': {'access-list': {'type': 'str'},
                                                                               'direction': {'choices': ['in',
                                                                                                         'out'],
                                                                                             'type': 'str'}},
                                                                   'type': 'list'},
                                                  'name': {'required': True,
                                                           'type': 'str'}},
                                      'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
