#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the mirror_session module
"""


class Mirror_sessionArgs(object):  # pylint: disable=R0903
    """The arg spec for the mirror_session module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'session': {'elements': 'dict',
                                    'mutually_exclusive': ['erspan', 'span'],
                                    'options': {'erspan': {'options': {'destination-address': {'type': 'str'},
                                                                       'direction': {'choices': ['rx',
                                                                                                 'tx',
                                                                                                 'both'],
                                                                                     'type': 'str'},
                                                                       'dscp': {'type': 'int'},
                                                                       'gre': {'type': 'str'},
                                                                       'source-address': {'type': 'str'},
                                                                       'source-interface': {'type': 'str'},
                                                                       'ttl': {'type': 'int'}},
                                                           'type': 'dict'},
                                                'name': {'required': True,
                                                         'type': 'str'},
                                                'span': {'elements': 'dict',
                                                         'options': {'destination-interface': {'required': True,
                                                                                               'type': 'str'},
                                                                     'direction': {'choices': ['rx',
                                                                                               'tx',
                                                                                               'both'],
                                                                                   'type': 'str'},
                                                                     'source-interface': {'type': 'str'}},
                                                         'type': 'list'}},
                                    'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
