#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the crm module
"""


class CrmArgs(object):  # pylint: disable=R0903
    """The arg spec for the crm module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'global': {'options': {'polling-interval': {'type': 'int'}},
                                   'type': 'dict'},
                        'resource': {'elements': 'dict',
                                     'options': {'high-threshold': {'type': 'int'},
                                                 'low-threshold': {'type': 'int'},
                                                 'name': {'choices': ['acl_group',
                                                                      'acl_group_counter',
                                                                      'acl_group_entry',
                                                                      'acl_group_table',
                                                                      'fdb',
                                                                      'ipv4_neighbor',
                                                                      'ipv4_nexthop',
                                                                      'ipv4_route',
                                                                      'ipv6_neighbor',
                                                                      'ipv6_nexthop',
                                                                      'ipv6_route',
                                                                      'nexthop_group_member',
                                                                      'nexthop_group_object'],
                                                          'required': True,
                                                          'type': 'str'},
                                                 'threshold-type': {'choices': ['percentage',
                                                                                'used',
                                                                                'free'],
                                                                    'type': 'str'}},
                                     'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
