#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the bgp_af module
"""


class Bgp_afArgs(object):  # pylint: disable=R0903
    """The arg spec for the bgp_af module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'bgp': {'elements': 'dict',
                                'options': {'address-family': {'elements': 'dict',
                                                               'options': {'advertise': {'options': {'ipv4': {'mutually_exclusive': [['gateway-ip',
                                                                                                                                      'route-map']],
                                                                                                              'options': {'gateway-ip': {'type': 'bool'},
                                                                                                                          'route-map': {'type': 'str'},
                                                                                                                          'unicast': {'type': 'bool'}},
                                                                                                              'type': 'dict'},
                                                                                                     'ipv6': {'mutually_exclusive': [['gateway-ip',
                                                                                                                                      'route-map']],
                                                                                                              'options': {'gateway-ip': {'type': 'bool'},
                                                                                                                          'route-map': {'type': 'str'},
                                                                                                                          'unicast': {'type': 'bool'}},
                                                                                                              'type': 'dict'}},
                                                                                         'type': 'dict'},
                                                                           'advertise-all-vni': {'type': 'bool'},
                                                                           'afi': {'choices': ['ipv4',
                                                                                               'ipv6',
                                                                                               'l2vpn'],
                                                                                   'required': True,
                                                                                   'type': 'str'},
                                                                           'aggregate': {'elements': 'dict',
                                                                                         'mutually_exclusive': [['as-set',
                                                                                                                 'origin',
                                                                                                                 'route-map',
                                                                                                                 'summary-only']],
                                                                                         'options': {'address': {'required': True,
                                                                                                                 'type': 'str'},
                                                                                                     'as-set': {'type': 'bool'},
                                                                                                     'origin': {'choices': ['egp',
                                                                                                                            'igp',
                                                                                                                            'incomplete'],
                                                                                                                'type': 'str'},
                                                                                                     'route-map': {'type': 'str'},
                                                                                                     'summary-only': {'type': 'bool'}},
                                                                                         'type': 'list'},
                                                                           'dampening': {'options': {'half-life-time': {'type': 'int'},
                                                                                                     'reuse-value': {'type': 'int'},
                                                                                                     'suppress-stable-route': {'type': 'int'},
                                                                                                     'suppress-value': {'type': 'int'}},
                                                                                         'required_together': [['half-life-time',
                                                                                                                'reuse-value',
                                                                                                                'suppress-value',
                                                                                                                'suppress-stable-route']],
                                                                                         'type': 'dict'},
                                                                           'distance': {'options': {'bgp': {'options': {'ebgp': {'type': 'int'},
                                                                                                                        'ibgp': {'type': 'int'},
                                                                                                                        'local': {'type': 'int'}},
                                                                                                            'type': 'dict'},
                                                                                                    'metric': {'elements': 'dict',
                                                                                                               'options': {'prefix': {'required': True,
                                                                                                                                      'type': 'str'},
                                                                                                                           'value': {'required': True,
                                                                                                                                     'type': 'int'}},
                                                                                                               'type': 'list'}},
                                                                                        'type': 'dict'},
                                                                           'max-path': {'options': {'ebgp': {'type': 'int'},
                                                                                                    'equal-cluster-length': {'type': 'bool'},
                                                                                                    'ibgp': {'type': 'int'}},
                                                                                        'required_by': {'equal-cluster-length': ['ibgp']},
                                                                                        'type': 'dict'},
                                                                           'network': {'elements': 'dict',
                                                                                       'options': {'backdoor': {'type': 'bool'},
                                                                                                   'prefix': {'required': True,
                                                                                                              'type': 'str'},
                                                                                                   'route-map': {'type': 'str'}},
                                                                                       'type': 'list'},
                                                                           'redistribute': {'elements': 'dict',
                                                                                            'options': {'instance-id': {'type': 'int'},
                                                                                                        'metric': {'type': 'int'},
                                                                                                        'protocol': {'choices': ['connected',
                                                                                                                                 'kernel',
                                                                                                                                 'ospf',
                                                                                                                                 'static',
                                                                                                                                 'table'],
                                                                                                                     'required': True,
                                                                                                                     'type': 'str'},
                                                                                                        'route-map': {'type': 'str'}},
                                                                                            'type': 'list'},
                                                                           'safi': {'choices': ['unicast',
                                                                                                'evpn'],
                                                                                    'required': True,
                                                                                    'type': 'str'},
                                                                           'table-map': {'type': 'str'}},
                                                               'type': 'list'},
                                            'asn': {'required': True,
                                                    'type': 'str'},
                                            'view': {'type': 'str'},
                                            'vrf': {'type': 'str'}},
                                'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
