---
- name: Playbook to configure Border Leaf nodes
  hosts: border_leaf_group
  gather_facts: no
 
  tasks:

    - name: Configure tenant_vrf & its interface
      celestica.sonic.vrf:
        config:
          vrf:
            - name: "{{tenant_vrf}}"
              vni: "{{vrf_vni}}"
              ipv4-router-id: "{{overlay_unique_lb_ip}}"
          interface:
            - name: "{{loopback1_interface}}"
              vrf: "{{tenant_vrf}}"
            - name: "Vlan{{tunnel_vlan}}"
              vrf: "{{tenant_vrf}}"

    - name: Configure Loopback IPs (underlay, overlay_ident_tun, overlay_unique)
      celestica.sonic.l3_interface:
        config:
          interface:
            - name: "{{loopback0_interface}}"
              ipv4: 
                addresses:
                  - address: "{{underlay_lb_ip}}/{{underlay_lb_ip_mask}}"
            - name: "{{loopback1_interface}}"
              ipv4: 
                addresses:
                  - address: "{{overlay_ident_tun_lb_ip}}/{{overlay_ident_tun_lb_ip_mask}}"
            - name: "{{loopback2_interface}}"
              ipv4: 
                addresses:
                  - address: "{{overlay_unique_lb_ip}}/{{overlay_unique_lb_ip_mask}}"
          
    - name: Configure link_local_ipv6 on other_site & same_site border_leaf_interface
      celestica.sonic.l3_interface:
        config:
          interface:
            - name: "{{other_site_border_leaf_interface}}"
              ipv6:
                link-local-only: true
            - name: "{{same_site_border_leaf_interface}}"
              ipv6:
                link-local-only: true

    - name: Configure link_local_ipv6
      celestica.sonic.l3_interface:
        config:
          interface:
            - name: "{{item}}"
              ipv6:
                link-local-only: true
      with_items: "{{spine_interfaces}}"

    - name: Configure BGP router-id, bestpath, ebgp-requires-policy on border_leaf_asn
      celestica.sonic.bgp:
        config:
          bgp:
            - asn: "{{border_leaf_asn}}"
              router-id: "{{underlay_lb_ip}}"
              ebgp-requires-policy: false
              bestpath:
                as-path:
                  multipath-relax: true

    - name: Configure BGP remote-as on other_site_border_leaf_interface & same_site_border_leaf
      celestica.sonic.bgp_neighbor:
        config:
          bgp:
            - asn: "{{border_leaf_asn}}" 
              neighbor:
                - id: "{{other_site_border_leaf_interface}}"
                  interface: true
                  remote-as: external
                - id: "{{same_site_border_leaf_interface}}"
                  interface: true
                  remote-as: internal

    - name: Configure BGP remote-as on spine_interfaces
      celestica.sonic.bgp_neighbor:
        config:
          bgp:
            - asn: "{{border_leaf_asn}}" 
              neighbor:                  
                - id: "{{item}}"
                  interface: true
                  remote-as: external               
      with_items: "{{spine_interfaces}}"

    - name: Configure BGP address family (redistribute connected & advertise-all-vni)
      celestica.sonic.bgp_af:
        config:
          bgp:
            - asn: "{{border_leaf_asn}}"
              address-family:
                - afi: ipv4
                  safi: unicast
                  redistribute:
                    - protocol: connected
                - afi: l2vpn
                  safi: evpn
                  advertise-all-vni: true

    - name: Configure BGP address family neighbor (neighbor <neigh_tag> activate) on other_site_border_leaf_interface & same_site_border_leaf_neighbor
      celestica.sonic.bgp_af_neighbor:
        config:
          bgp:
            - asn: "{{border_leaf_asn}}"
              address-family:
                - afi: l2vpn
                  safi: evpn
                  neighbor:
                    - id: "{{other_site_border_leaf_interface}}"
                      activate: true
                    - id: "{{same_site_border_leaf_interface}}"
                      activate: true                      

    - name: Configure BGP address family neighbor (neighbor <spine_interfaces> activate) on spine_interfaces
      celestica.sonic.bgp_af_neighbor:
        config:
          bgp:
            - asn: "{{border_leaf_asn}}"
              address-family:
                - afi: l2vpn
                  safi: evpn
                  neighbor:
                    - id: "{{item}}"
                      activate: true                     
      with_items: "{{spine_interfaces}}"                

    - name: Configure VxLAN (vxlan-profile, interface [src-ip] , tunnel_vlan - vrf_vni )
      celestica.sonic.vxlan:
        config:
          vxlan-profile: true
          interface:
            - name: "vtep{{vtep_number}}"
              source-ip: "{{overlay_ident_tun_lb_ip}}"
              vni:
                - vni-id: "{{vrf_vni}}"
                  vlan-id: "{{tunnel_vlan}}"

    - name: Configure BGP with vrf ebgp-requires-policy on tenant_asn
      celestica.sonic.bgp:
        config:
          bgp:
            - asn: "{{tenant_asn}}"
              vrf: "{{tenant_vrf}}"
              ebgp-requires-policy: false

    - name: Configure sdwan_ip_address BGP neighbors on tenant_asn
      celestica.sonic.bgp_neighbor:
        config:
          bgp:
            - asn: "{{tenant_asn}}"
              vrf: "{{tenant_vrf}}"
              neighbor:
                - id: "{{sdwan_ip_address}}"
                  remote-as: "{{sdwan_asn}}"

    - name: Configure BGP address family (redistribute connected) on tenant_asn
      celestica.sonic.bgp_af:
        config:
          bgp:
            - asn: "{{tenant_asn}}"
              vrf: "{{tenant_vrf}}"
              address-family:
                - afi: ipv4
                  safi: unicast
                  redistribute:
                    - protocol: connected

    - name: Configure firewall_vlans - VRF
      celestica.sonic.vrf:
        config:
          interface:
            - name: "Vlan{{item.key}}"
              vrf: "{{tenant_vrf}}"
      loop: "{{ lookup('ansible.builtin.dict', firewall_vlans) }}"

    - name: Configure firewall_vlans - Trunk
      celestica.sonic.l2_interface:
        config:
          interface:
            - name: "{{item.value.trunk_interface}}"
              trunk:
                - vlan: "{{item.key}}"
      loop: "{{ lookup('ansible.builtin.dict', firewall_vlans) }}"

    - name: Configure VxLAN firewall_vlans - VNI
      celestica.sonic.vxlan:
        config:
          interface:
            - name: "vtep{{vtep_number}}"
              vni:
                - vni-id: "{{item.value.vlan_vni}}"
                  vlan-id: "{{item.key}}"
      loop: "{{ lookup('ansible.builtin.dict', firewall_vlans) }}"

    - name: Merge MCLAG peer_link Configuration
      celestica.sonic.portchannel:
        config:
          interface:
            - name: "{{peer_link}}"

    - name: Configure MCLAG peer-link members
      celestica.sonic.interface:
        config:
          interface:
            - name: "{{item.key}}"
              channel-group: "{{item.value.channel_group}}"
      loop: "{{ lookup('ansible.builtin.dict', lag_members) }}"

    - name: Configure MCLAG Domain (peerlink, peer-ip, src-ip, sys-mac)
      celestica.sonic.mclag:
        config:
          domain:
            - id: "{{mclag_domain_id}}"
              peer-ip: "{{peer_underlay_lb_ip}}"
              peer-link: "{{peer_link}}"
              source-ip: "{{underlay_lb_ip}}"
              system-mac: "{{system_mac}}"
