#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the qos_wred module
"""


class Qos_wredArgs(object):  # pylint: disable=R0903
    """The arg spec for the qos_wred module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'interface': {'elements': 'dict',
                                      'options': {'name': {'required': True,
                                                           'type': 'str'},
                                                  'profile': {'elements': 'dict',
                                                              'options': {'name': {'type': 'str'},
                                                                          'queue': {'required': True,
                                                                                    'type': 'int'}},
                                                              'type': 'list'}},
                                      'type': 'list'},
                        'wred-profile': {'elements': 'dict',
                                         'options': {'name': {'required': True,
                                                              'type': 'str'},
                                                     'random-detect': {'options': {'color': {'elements': 'dict',
                                                                                             'options': {'drop-probability': {'type': 'int'},
                                                                                                         'id': {'choices': ['green',
                                                                                                                            'red',
                                                                                                                            'yellow'],
                                                                                                                'required': True,
                                                                                                                'type': 'str'},
                                                                                                         'max-threshold': {'type': 'int'},
                                                                                                         'min-threshold': {'type': 'int'}},
                                                                                             'type': 'list'},
                                                                                   'ecn': {'choices': ['all',
                                                                                                       'green',
                                                                                                       'red',
                                                                                                       'yellow',
                                                                                                       'green-red',
                                                                                                       'green-yellow',
                                                                                                       'yellow-red',
                                                                                                       'none'],
                                                                                           'type': 'str'}},
                                                                       'type': 'dict'}},
                                         'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
