#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the bgp_af_neighbor module
"""


class Bgp_af_neighborArgs(object):  # pylint: disable=R0903
    """The arg spec for the bgp_af_neighbor module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'bgp': {'elements': 'dict',
                                'options': {'address-family': {'elements': 'dict',
                                                               'options': {'afi': {'choices': ['ipv4',
                                                                                               'ipv6',
                                                                                               'l2vpn'],
                                                                                   'required': True,
                                                                                   'type': 'str'},
                                                                           'neighbor': {'elements': 'dict',
                                                                                        'mutually_exclusive': [['allowas-in-asn',
                                                                                                                'allowas-in-origin']],
                                                                                        'options': {'activate': {'type': 'bool'},
                                                                                                    'addpath-tx-all-paths': {'type': 'bool'},
                                                                                                    'addpath-tx-bestpath-per-as': {'type': 'bool'},
                                                                                                    'allowas-in': {'type': 'bool'},
                                                                                                    'allowas-in-asn': {'type': 'int'},
                                                                                                    'allowas-in-origin': {'type': 'bool'},
                                                                                                    'as-override': {'type': 'bool'},
                                                                                                    'attribute-unchanged': {'type': 'bool'},
                                                                                                    'attribute-unchanged-type': {'choices': ['as-path',
                                                                                                                                             'med',
                                                                                                                                             'next-hop'],
                                                                                                                                 'type': 'str'},
                                                                                                    'capability': {'options': {'orf': {'options': {'prefix-list': {'choices': ['both',
                                                                                                                                                                               'send',
                                                                                                                                                                               'receive'],
                                                                                                                                                                   'type': 'str'}},
                                                                                                                                       'type': 'dict'}},
                                                                                                                   'type': 'dict'},
                                                                                                    'default-originate': {'type': 'bool'},
                                                                                                    'default-originate-route-map': {'type': 'str'},
                                                                                                    'id': {'required': True,
                                                                                                           'type': 'str'},
                                                                                                    'maximum-prefix': {'type': 'int'},
                                                                                                    'maximum-prefix-force': {'type': 'bool'},
                                                                                                    'maximum-prefix-out': {'type': 'int'},
                                                                                                    'maximum-prefix-restart': {'type': 'int'},
                                                                                                    'maximum-prefix-threshold': {'type': 'int'},
                                                                                                    'maximum-prefix-warning-only': {'type': 'bool'},
                                                                                                    'next-hop-self': {'type': 'bool'},
                                                                                                    'next-hop-self-force': {'type': 'bool'},
                                                                                                    'remove-private-as': {'type': 'bool'},
                                                                                                    'remove-private-as-all': {'type': 'bool'},
                                                                                                    'remove-private-as-replace-as': {'type': 'bool'},
                                                                                                    'route-reflector-client': {'type': 'bool'},
                                                                                                    'route-server-client': {'type': 'bool'},
                                                                                                    'send-community': {'choices': ['all',
                                                                                                                                   'both',
                                                                                                                                   'extended',
                                                                                                                                   'large',
                                                                                                                                   'standard'],
                                                                                                                       'type': 'str'},
                                                                                                    'soft-reconfiguration': {'options': {'inbound': {'type': 'bool'}},
                                                                                                                             'type': 'dict'},
                                                                                                    'unsuppress-map': {'type': 'str'},
                                                                                                    'weight': {'type': 'int'}},
                                                                                        'required_by': {'allowas-in-origin': ['allowas-in'],
                                                                                                        'default-originate-route-map': ['default-originate'],
                                                                                                        'next-hop-self-force': ['next-hop-self'],
                                                                                                        'remote-private-as-all': ['remote-private-as'],
                                                                                                        'remote-private-as-replace-as': ['remote-private-as']},
                                                                                        'type': 'list'},
                                                                           'safi': {'choices': ['unicast',
                                                                                                'evpn'],
                                                                                    'required': True,
                                                                                    'type': 'str'}},
                                                               'type': 'list'},
                                            'asn': {'required': True,
                                                    'type': 'str'},
                                            'view': {'type': 'str'},
                                            'vrf': {'type': 'str'}},
                                'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
