#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the bgp_neighbor module
"""


class Bgp_neighborArgs(object):  # pylint: disable=R0903
    """The arg spec for the bgp_neighbor module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'bgp': {'elements': 'dict',
                                'mutually_exclusive': [['vrf', 'view']],
                                'options': {'asn': {'required': True,
                                                    'type': 'str'},
                                            'neighbor': {'elements': 'dict',
                                                         'mutually_exclusive': [['peer-group-enable',
                                                                                 'peer-group'],
                                                                                ['override-capability',
                                                                                 'strict-capability-match']],
                                                         'options': {'advertisement-interval': {'type': 'int'},
                                                                     'capability': {'options': {'dynamic': {'type': 'bool'},
                                                                                                'extended-nexthop': {'type': 'bool'}},
                                                                                    'type': 'dict'},
                                                                     'description': {'type': 'str'},
                                                                     'disable-capability-negotiate': {'type': 'bool'},
                                                                     'disable-connected-check': {'type': 'bool'},
                                                                     'enforce-first-as': {'type': 'bool'},
                                                                     'graceful-restart': {'type': 'bool'},
                                                                     'graceful-restart-helper': {'type': 'bool'},
                                                                     'id': {'required': True,
                                                                            'type': 'str'},
                                                                     'interface': {'type': 'bool'},
                                                                     'local-as': {'type': 'int'},
                                                                     'override-capability': {'type': 'bool'},
                                                                     'passive': {'type': 'bool'},
                                                                     'password': {'type': 'str'},
                                                                     'peer-group': {'type': 'str'},
                                                                     'peer-group-enable': {'type': 'bool'},
                                                                     'port': {'type': 'int'},
                                                                     'remote-as': {'type': 'str'},
                                                                     'sender-as-path-loop-detection': {'type': 'bool'},
                                                                     'shutdown': {'type': 'bool'},
                                                                     'shutdown-message': {'type': 'str'},
                                                                     'shutdown-rtt': {'type': 'int'},
                                                                     'solo': {'type': 'bool'},
                                                                     'strict-capability-match': {'type': 'bool'},
                                                                     'timers': {'options': {'connect': {'type': 'int'},
                                                                                            'hold': {'type': 'int'},
                                                                                            'keep-alive': {'type': 'int'}},
                                                                                'type': 'dict'},
                                                                     'ttl-security': {'options': {'hops': {'type': 'int'}},
                                                                                      'type': 'dict'},
                                                                     'update-source': {'type': 'str'},
                                                                     'v6only': {'type': 'bool'}},
                                                         'type': 'list'},
                                            'view': {'type': 'str'},
                                            'vrf': {'type': 'str'}},
                                'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
