#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for bgp
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: bgp
version_added: 1.0.0
short_description: Resource module to configure global BGP.
description:
  - This module configures and manages BGP on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of BGP configurations.
    type: dict
    suboptions:
      # BGP config
      bgp:
        description:
          - BGP configuration
        type: list
        elements: dict
        suboptions:
          asn:
            description:
              - ASN number. Range is 1-4294967295.
            type: str
            required: true
          vrf:
            description:
              - VRF name, shall be prefixed with 'Vrf' pattern. Maximum of 15 characters.
            type: str
          view:
            description:
              - View name.
            type: str
          always-compare-med:
            description:
              - Use MED to compare for routes even when received across ASes.
            type: bool
          bestpath:
            description:
              - Bestpath configurations.
            type: dict
            suboptions:
              as-path:
                description:
                  - AS path configurations.
                type: dict
                suboptions:
                  confed:
                    description:
                      - Match length of confederation path set and sequence.
                    type: bool
                  multipath-relax:
                    description:
                      - Allow load sharing across routes that have different AS paths (but same length).
                    type: bool
                  multipath-relax-as-set:
                    description:
                      - Option to generate an AS_SET or not.
                    type: bool
              bandwidth:
                description:
                  - Link bandwidth configuration options.
                  - default-weight-for-missing indicates assigning a low default weight (value 1) to paths not having link bandwidth
                  - ignore indicates ignoring link bandwidth (i.e., do regular ECMP, not weighted)
                  - skip-missing indicates ignoring paths without link bandwidth for ECMP (if other paths have it)
                type: str
                choices: [default-weight-for-missing, ignore, skip-missing]
              compare-routerid:
                description:
                  - Use routerid as tie breaker for bestpath selection.
                type: bool
              med:
                description:
                  - Bestpath MED related configurations.
                type: dict
                suboptions:
                  confed:
                    description:
                      - Compare MED among confederation paths.
                    type: bool
                  missing-as-worst:
                    description:
                      - Treat missing MED as the least preferred one.
                    type: bool
              peer-type-multipath-relax:
                description:
                  - Use routerid as tie breaker for bestpath selection.
                type: bool
          client-to-client-reflection:
            description:
              - Option to enable or disable client to client route reflection.
            type: bool
          cluster-id:
            description:
              - Route-Reflector cluster-id in IP address format.
            type: str
          confederation:
            description:
              - AS confederation configuration.
            type: dict
            suboptions:
              identifier:
                description:
                  - AS confederation identifier. Range is 1-4294967295.
                type: int
              peers:
                description:
                  - Number of peer AS in BGP confederation. Range is 1-4294967295.
                type: int
          default:
            description:
              - Default settings.
            type: dict
            suboptions:
              ipv4-unicast:
                description:
                  - Option to enable or disable ipv4-unicast as default.
                type: bool
              local-preference:
                description:
                  - Local preference (higher=more preferred) configuration. Range is 1-4294967295.
                type: int
              shutdown:
                description:
                  - Enable or disable default BGP shutdown.
                type: bool
          deterministic-med:
            description:
              - Deterministic Route selection with MED.
            type: bool
          disable-ebgp-connected-route-check:
            description:
              - Option to disable connection verification process for EBGP peers.
            type: bool
          ebgp-requires-policy:
            description:
              - Apply Incoming/Outgoing Filters to eBGP session (RFC8212).
            type: bool
          fast-external-failover:
            description:
              - Immediately reset session if a link to a directly connected external peer goes down.
            type: bool
          graceful-restart:
            description:
              - Graceful restart configuration.
            type: dict
            suboptions:
              disable-eor:
                description:
                  - Option to disable End-Of-RIB generation for graceful gestart.
                type: bool
              preserve-fw-state:
                description:
                  - Enable/disable F flag in graceful restart capability.
                type: bool
              restart-time:
                description:
                  - Time in seconds to wait to delete stale routes before BGP OPEN. Range is 0-4095.
                type: int
              rib-stale-time:
                description:
                  - Time in seconds for which Stale Routes kept in RIB. Range is 1-3600.
                type: int
              select-defer-time:
                description:
                  - Deferal time in seconds. Range is 0-3600.
                type: int
              stalepath-time:
                description:
                  - Time in seconds to hold onto restarting router's stale path. Range is 1-4095.
                type: int
          graceful-restart-disable:
            description:
              - Option to disable global graceful restart.
            type: bool
          graceful-shutdown:
            description:
              - BGP graceful shutdown as per RFC 8326.
            type: bool
          listen:
            description:
              - BGP dynamic neighbors listen configuration.
            type: dict
            suboptions:
              limit:
                description:
                  - Maximum number of BGP dynamic neighbors that can be created. Range is 1-5000.
                type: int
              range:
                description:
                  - Configure BGP dynamic neighbors listen range.
                type: list
                elements: dict
                suboptions:
                  address:
                    description:
                      - IPv4 or IPv6 address with Prefix.
                    type: str
                  peer-group:
                    description:
                      - Peer group name.
                    type: str
          log-neighbor-changes:
            description:
              - Option to enable or disable logging of neighbor up/down and reset reason.
            type: bool
          max-med:
            description:
              - Advertise routes with max-med.
            type: dict
            suboptions:
              administrative:
                description:
                  - Administratively applied, for an indefinite period.
                type: bool
              administrative-max:
                description:
                  - Max MED value for adminstrative. Range is 0-4294967295.
                type: int
              on-startup:
                description:
                  - Effective on a startup.
                type: dict
                suboptions:
                  startup-max:
                    description:
                      - Max MED value for startup. Range is 0-4294967295.
                    type: int
                  startup-period:
                    description:
                      - Time period in seconds for max-med. Range is 5-86400.
                    type: int
          network-import-check:
            description:
              - Option to enable or disable import check, configured network must exist in RIB.
            type: bool
          reject-as-sets:
            description:
              - Option to discard routes incoming/outgoing with AS_SET or CONFED_SET.
            type: bool
          route-map-delay-timer:
            description:
              - Time in seconds to wait before processing route-map changes.
              - Range 0-600, 0 disables the timer, no route updates happen when route-maps change.
            type: int
          router-reflector-allow-outbound-policy:
            description:
              - Allow modifications made by out route-map on ibgp neighbors.
            type: bool
          router-id:
            description:
              - Router IP address.
            type: str
          session-dscp:
            description:
              - Override default (C0) bgp TCP session DSCP value. Range is 0-63.
            type: int
          shutdown:
            description:
              - Administrative shutdown of all BGP peers.
            type: bool
          shutdown-message:
            description:
              - Add a shutdown message (RFC 8203).
            type: str
          coalesce-time:
            description:
              - Subgroup coalesce timer value (in ms). Range is 0-4294967295.
            type: int
          timers:
            description:
              - Routing timers configuration.
            type: dict
            suboptions:
              keep-alive:
                description:
                  - Keepalive interval. Range is 0-64435.
                type: int
              hold:
                description:
                  - Hold interval. Range is 0-65535.
                type: int
          update-delay-max-delay:
            description:
              - Force initial delay for best-path and updates.
              - Max delay in seconds, Range is 0-3600.
            type: int
          update-delay-establish-wait:
            description:
              - Force initial delay for best-path and updates.
              - Establish wait in seconds, Range is 1-3600.
            type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config bgp
# !
# frr log syslog informational
# frr log facility local4
# !
# router bgp 1
#  bgp router-id 1.1.1.1
#  no bgp ebgp-requires-policy
#  bgp bestpath as-path multipath-relax
# exit
# !
# router bgp 1 vrf Vrf1
#  neighbor tag1 peer-group
#  neighbor tag1 remote-as internal
# exit
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge global BGP Configuration
      celestica.sonic.bgp:
        config:
          bgp:
            - asn: 1
              always-compare-med: true
              bestpath:
                as-path:
                  confed: true
                  multipath-relax: true
              client-to-client-reflection: false
              cluster-id: 20.1.1.1
              default:
                ipv4-unicast: false
              ebgp-requires-policy: false
              fast-external-failover: false
              graceful-shutdown: true
              max-med:
                administrative: true
              router-id: 10.1.1.1
            - asn: 1
              vrf: Vrf1
              bestpath:
                as-path:
                  multipath-relax: true
                  multipath-relax-as-set: true
              confederation:
                identifier: 5
              deterministic-med: true
              disable-ebgp-connected-route-check: true
              graceful-restart:
                preserve-fw-state: true
                restart-time: 50
              listen:
                limit: 10
                range:
                  - address: 10.1.1.0/24
                    peer-group: tag1
              max-med:
                administrative: true
                administrative-max: 4
              router-reflector-allow-outbound-policy: true
              shutdown: true
              update-delay-max-delay: 6
              update-delay-establish-wait: 5
            - asn: 1
              view: view2
              bestpath:
                bandwidth: skip-missing
                med:
                  confed: true
                  missing-as-worst: true
                compare-routerid: true
                peer-type-multipath-relax: true
              confederation:
                identifier: 5
              default:
                local-preference: 5
              graceful-restart:
                rib-stale-time: 40
                select-defer-time: 30
                stalepath-time: 20
              log-neighbor-changes: true
              network-import-check: false
              reject-as-sets: true
              coalesce-time: 2
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  no bgp fast-external-failover
#  bgp router-id 10.1.1.1
#  bgp always-compare-med
#  no bgp ebgp-requires-policy
#  no bgp default ipv4-unicast
#  no bgp client-to-client reflection
#  bgp cluster-id 20.1.1.1
#  bgp max-med administrative
#  bgp graceful-shutdown
#  bgp graceful-restart-disable
#  bgp bestpath as-path confed
#  bgp bestpath as-path multipath-relax
# exit
# !
# router bgp 1 vrf Vrf1
#  bgp disable-ebgp-connected-route-check
#  bgp confederation identifier 5
#  bgp deterministic-med
#  update-delay 6 5
#  bgp max-med administrative 4
#  bgp graceful-restart restart-time 50
#  bgp graceful-restart preserve-fw-state
#  bgp bestpath as-path multipath-relax as-set
#  bgp route-reflector allow-outbound-policy
#  neighbor tag1 peer-group
#  neighbor tag1 remote-as internal
#  bgp listen limit 10
#  bgp listen range 10.1.1.0/24 peer-group tag1
#  bgp shutdown
# exit
# !
# router bgp 1 view view2
#  bgp log-neighbor-changes
#  bgp reject-as-sets
#  bgp default local-preference 5
#  bgp confederation identifier 5
#  coalesce-time 2
#  bgp graceful-restart stalepath-time 20
#  bgp graceful-restart select-defer-time 30
#  bgp graceful-restart rib-stale-time 40
#  bgp bestpath compare-routerid
#  bgp bestpath med confed missing-as-worst
#  bgp bestpath peer-type multipath-relax
#  bgp bestpath bandwidth skip-missing
#  no bgp network import-check
# exit
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  no bgp fast-external-failover
#  bgp router-id 10.1.1.1
#  bgp always-compare-med
#  no bgp ebgp-requires-policy
#  no bgp default ipv4-unicast
#  no bgp client-to-client reflection
#  bgp cluster-id 20.1.1.1
#  bgp max-med administrative
#  bgp graceful-shutdown
#  bgp graceful-restart-disable
#  bgp bestpath as-path confed
#  bgp bestpath as-path multipath-relax
# exit
# !
# router bgp 1 vrf Vrf1
#  bgp disable-ebgp-connected-route-check
#  bgp confederation identifier 5
#  bgp deterministic-med
#  update-delay 6 5
#  bgp max-med administrative 4
#  bgp graceful-restart restart-time 50
#  bgp graceful-restart preserve-fw-state
#  bgp bestpath as-path multipath-relax as-set
#  bgp route-reflector allow-outbound-policy
#  neighbor tag1 peer-group
#  neighbor tag1 remote-as internal
#  bgp listen limit 10
#  bgp listen range 10.1.1.0/24 peer-group tag1
#  bgp shutdown
# exit
# !
# router bgp 1 view view2
#  bgp log-neighbor-changes
#  bgp reject-as-sets
#  bgp default local-preference 5
#  bgp confederation identifier 5
#  coalesce-time 2
#  bgp graceful-restart stalepath-time 20
#  bgp graceful-restart select-defer-time 30
#  bgp graceful-restart rib-stale-time 40
#  bgp bestpath compare-routerid
#  bgp bestpath med confed missing-as-worst
#  bgp bestpath peer-type multipath-relax
#  bgp bestpath bandwidth skip-missing
#  no bgp network import-check
# exit
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete global BGP Configuration
      celestica.sonic.bgp:
        config:
          bgp:
            - asn: 1
              always-compare-med: true
              bestpath:
                as-path:
                  confed: true
                  multipath-relax: true
              client-to-client-reflection: false
              cluster-id: 20.1.1.1
              default:
                ipv4-unicast: false
              ebgp-requires-policy: false
              fast-external-failover: false
              max-med:
                administrative: true
              router-id: 10.1.1.1
            - asn: 1
              vrf: Vrf1
              bestpath:
                as-path:
                  multipath-relax: true
                  multipath-relax-as-set: true
              confederation:
                identifier: 5
              deterministic-med: true
              disable-ebgp-connected-route-check: true
              listen:
                limit: 10
                range:
                  - address: 10.1.1.0/24
                    peer-group: tag1
              max-med:
                administrative: true
                administrative-max: 4
              router-reflector-allow-outbound-policy: true
              shutdown: true
              update-delay-max-delay: 6
              update-delay-establish-wait: 5
            - asn: 1
              view: view2

        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  bgp graceful-shutdown
#  bgp graceful-restart-disable
# exit
# !
# router bgp 1 vrf Vrf1
#  bgp graceful-restart restart-time 50
#  bgp graceful-restart preserve-fw-state
#  neighbor tag1 peer-group
#  neighbor tag1 remote-as internal
# exit
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.bgp.bgp import BgpArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.bgp.bgp import Bgp


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=BgpArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
