#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for bgp_neighbor
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: bgp_neighbor
version_added: 1.0.0
short_description: Resource module to configure BGP neighbors.
description:
  - This module configures and manages BGP neighbors on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of BGP neighbor configurations.
    type: dict
    suboptions:
      # BGP neighbor config
      bgp:
        description:
          - BGP configuration
        type: list
        elements: dict
        suboptions:
          asn:
            description:
              - ASN number. Range is 1-4294967295.
            type: str
            required: true
          vrf:
            description:
              - VRF name, shall be prefixed with 'Vrf' pattern. Maximum of 15 characters.
            type: str
          view:
            description:
              - View name.
            type: str
          neighbor:
            description:
              - BGP neighbor configuration
            type: list
            elements: dict
            suboptions:
              id:
                description:
                  - Neighbor identifier
                  - Name, Interface name and IPv4 address are allowed.
                type: str
                required: true
              advertisement-interval:
                description:
                  - Minimum interval between sending BGP routing updates, Range is 0-600.
                type: int
              capability:
                description:
                  - Advertise capability to the peer.
                type: dict
                suboptions:
                  dynamic:
                    description:
                      - Advertise dynamic capability to this neighbor.
                    type: bool
                  extended-nexthop:
                    description:
                      - Advertise extended next-hop capability to the peer.
                    type: bool
              description:
                description:
                  - Neighbor specific description. Maximum of 80 characters.
                type: str
              disable-connected-check:
                description:
                  - Represents one-hop away EBGP peer using loopback address.
                type: bool
              disable-capability-negotiate:
                description:
                  - Option to disable capability negotiation.
                type: bool
              enforce-first-as:
                description:
                  - Enforce the first AS for EBGP routes.
                type: bool
              # Add required_by while enabling these options
              # ebgp-multihop:
              #   description:
              #     - Allow EBGP neighbors not on directly connected networks.
              #   type: bool
              # ebgp-multihop-max-hops:
              #   description:
              #     - EBGP neighbors max hops count, Range is 1-255.
              #   type: int
              graceful-restart:
                description:
                  - Enable BGP graceful restart functionality at the peer level.
                type: bool
              graceful-restart-helper:
                description:
                  - Enable BGP graceful restart helper only functionality at the peer level.
                type: bool
              local-as:
                description:
                  - Local AS number. Range is 1-4294967295.
                type: int
              override-capability:
                description:
                  - Override capability negotiation result.
                type: bool
              passive:
                description:
                  - Option not to send open messages to this neighbor.
                type: bool
              password:
                description:
                  - MD5 password value in plain-text.
                type: str
              interface:
                description:
                  - Option to configure unnumbered BGP peer.
                type: bool
              v6only:
                description:
                  - Option to enable BGP with v6 link-local only.
                  - Valid only when interface is set.
                type: bool
              remote-as:
                description:
                  - Remote AS configuration
                  - Allowed values - ASN number (Range is 1-4294967295), 'external' and 'internal'
                  - external indicates 'Enable eBGP Peer'
                  - internal indicates 'Enable iBGP Peer'
                type: str
              peer-group-enable:
                description:
                  - Option to configure current neighbor as peer-group.
                type: bool
              peer-group:
                description:
                  - Peer group name.
                type: str
              port:
                description:
                  - BGP port of neighbor. Range is 0-65535.
                type: int
              sender-as-path-loop-detection:
                description:
                  - Detect AS loops before sending to neighbor.
                type: bool
              shutdown:
                description:
                  - Administratively shutdown this neighbor.
                type: bool
              shutdown-message:
                description:
                  - Add a shutdown message (RFC 8203).
                type: str
              shutdown-rtt:
                description:
                  - Shutdown if round-trip-time is higher than expected. Range is 1-65535.
                type: int
              solo:
                description:
                  - Solo peer - part of its own update group.
                type: bool
              strict-capability-match:
                description:
                  - Strict capability negotiation match.
                type: bool
              timers:
                description:
                  - BGP per neighbor timers configuration.
                type: dict
                suboptions:
                  connect:
                    description:
                      - Connect interval. Range is 1-65535.
                    type: int
                  keep-alive:
                    description:
                      - Keepalive interval. Range is 0-65535.
                    type: int
                  hold:
                    description:
                      - Hold interval. Range is 0-65535.
                    type: int
              ttl-security:
                description:
                  - TTL security related configurations.
                type: dict
                suboptions:
                  hops:
                    description:
                      - Specify the maximum number of hops to the BGP peer, Range is 1-254.
                    type: int
              update-source:
                description:
                  - Source of routing updates.
                  - IP address (both v4 and v6) and interface name are allowed.
                type: str

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  neighbor peer1 peer-group
#  neighbor 10.1.1.1 peer-group peer1
# exit
# !
# router bgp 1 vrf Vrf1
#  neighbor peer1 peer-group
#  neighbor 11::22 peer-group peer1
# exit
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge BGP Neighbors Configuration
      celestica.sonic.bgp_neighbor:
        config:
          bgp:
            - asn: 1
              neighbor:
                - id: 10.1.1.1
                  advertisement-interval: 2
                  capability:
                    dynamic: true
                  description: bgp_neigbor
                  disable-capability-negotiate: true
                  enforce-first-as: true
                  graceful-restart: true
                  local-as: 2
                  passive: true
                  remote-as: external
                  port: 25
                  sender-as-path-loop-detection: true
                  shutdown: true
                  strict-capability-match: true
                  timers:
                    connect: 2
                    keep-alive: 1
                    hold: 4
                  ttl-security:
                    hops: 2
                  update-source: 20.1.1.1
                - id: Ethernet0
                  interface: true
                  v6only: true
                  remote-as: internal
            - asn: 1
              vrf: Vrf1
              neighbor:
                - id: 11::22
                  advertisement-interval: 2
                  override-capability: true
                  timers:
                    keep-alive: 1
                    hold: 4
                  graceful-restart-helper: true
                  disable-connected-check: true
            - asn: 1
              view: view1
              neighbor:
                - id: peer2
                  peer-group-enable: true
                - id: 10.2.2.2
                  peer-group: peer2
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  neighbor peer1 peer-group
#  neighbor 10.1.1.1 remote-as external
#  neighbor 10.1.1.1 peer-group peer1
#  neighbor 10.1.1.1 local-as 2
#  neighbor 10.1.1.1 description bgp_neigbor
#  neighbor 10.1.1.1 port 25
#  neighbor 10.1.1.1 passive
#  neighbor 10.1.1.1 ttl-security hops 2
#  neighbor 10.1.1.1 enforce-first-as
#  neighbor 10.1.1.1 update-source 20.1.1.1
#  neighbor 10.1.1.1 advertisement-interval 2
#  neighbor 10.1.1.1 timers 1 4
#  neighbor 10.1.1.1 timers connect 2
#  neighbor 10.1.1.1 capability dynamic
#  neighbor 10.1.1.1 dont-capability-negotiate
#  neighbor 10.1.1.1 strict-capability-match
#  neighbor 10.1.1.1 sender-as-path-loop-detection
#  neighbor 10.1.1.1 graceful-restart
#  neighbor Ethernet0 interface v6only remote-as internal
# exit
# !
# router bgp 1 vrf Vrf1
#  neighbor peer1 peer-group
#  neighbor 11::22 peer-group peer1
#  neighbor 11::22 disable-connected-check
#  neighbor 11::22 advertisement-interval 2
#  neighbor 11::22 timers 1 4
#  neighbor 11::22 override-capability
#  neighbor 11::22 graceful-restart-helper
# exit
# !
# router bgp 1 view view1
#  neighbor peer2 peer-group
#  neighbor 10.2.2.2 peer-group peer2
# exit
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  neighbor peer1 peer-group
#  neighbor 10.1.1.1 remote-as external
#  neighbor 10.1.1.1 peer-group peer1
#  neighbor 10.1.1.1 local-as 2
#  neighbor 10.1.1.1 description bgp_neigbor
#  neighbor 10.1.1.1 port 25
#  neighbor 10.1.1.1 passive
#  neighbor 10.1.1.1 ttl-security hops 2
#  neighbor 10.1.1.1 enforce-first-as
#  neighbor 10.1.1.1 update-source 20.1.1.1
#  neighbor 10.1.1.1 advertisement-interval 2
#  neighbor 10.1.1.1 timers 1 4
#  neighbor 10.1.1.1 timers connect 2
#  neighbor 10.1.1.1 capability dynamic
#  neighbor 10.1.1.1 dont-capability-negotiate
#  neighbor 10.1.1.1 strict-capability-match
#  neighbor 10.1.1.1 sender-as-path-loop-detection
#  neighbor 10.1.1.1 graceful-restart
#  neighbor Ethernet0 interface v6only remote-as internal
# exit
# !
# router bgp 1 vrf Vrf1
#  neighbor peer1 peer-group
#  neighbor 11::22 peer-group peer1
#  neighbor 11::22 disable-connected-check
#  neighbor 11::22 advertisement-interval 2
#  neighbor 11::22 timers 1 4
#  neighbor 11::22 override-capability
#  neighbor 11::22 graceful-restart-helper
# exit
# !
# router bgp 1 view view1
#  neighbor peer2 peer-group
#  neighbor 10.2.2.2 peer-group peer2
# exit
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete BGP Neighbors Configuration
      celestica.sonic.bgp_neighbor:
        config:
          bgp:
            - asn: 1
              neighbor:
                - id: 10.1.1.1
                  advertisement-interval: 2
                  description: bgp_neigbor
                  disable-capability-negotiate: true
                  enforce-first-as: true
                  graceful-restart: true
                  local-as: 2
                  passive: true
                  port: 25
                  sender-as-path-loop-detection: true
                  shutdown: true
                  strict-capability-match: true
                  timers:
                    keep-alive: 1
                    hold: 4
                  ttl-security:
                    hops: 2
                  update-source: 20.1.1.1
                - id: Ethernet0
                  interface: true
                  v6only: true
                  remote-as: internal
            - asn: 1
              vrf: Vrf1
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  neighbor peer1 peer-group
#  neighbor 10.1.1.1 remote-as external
# exit
# !
# router bgp 1 view view1
#  neighbor peer2 peer-group
#  neighbor 10.2.2.2 peer-group peer2
# exit
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.bgp_neighbor.bgp_neighbor import Bgp_neighborArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.bgp_neighbor.bgp_neighbor import Bgp_neighbor


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Bgp_neighborArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp_neighbor(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
