#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for bgp_community
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: bgp_community
version_added: 1.0.0
short_description: Resource module to configure BGP community list.
description:
  - This module configures and manages BGP community list on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of community list configurations.
    type: dict
    suboptions:
      # community-list config
      community-list:
        description:
          - BGP community list configurations.
        type: list
        elements: dict
        suboptions:
          id:
            description:
              - Community list identifier.
              - Standard numbers (1-99), Extended numbers (100-500) are allowed.
              - User defind name is allowed only when 'type' is set.
            type: str
            required: true
          type:
            description:
              - Community list type.
              - User defind name in 'id' is allowed only when 'type' is set.
            type: str
            choices: [expanded, standard]
          # Sequence numbers under BGP community-list config
          sequence-numbers:
            description:
              - Seqeuce number under community list configuration
            type: list
            elements: dict
            suboptions:
              seq:
                description:
                  - Sequence number. Range is 1-4294967295.
                type: int
                required: true
              action:
                description:
                  - Action for this community list.
                type: str
                choices: [deny, permit]
                required: true
              number:
                description:
                  - Community number in AA:NN format (where AA and NN are (0-65535)) or local-AS|no-advertise|no-export|internet or additive.
                  - Comma separated community list are allowed.
                type: str
                required: true

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config bgp
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge BGP Community Configuration
      celestica.sonic.bgp_community:
        config:
          community-list:
            - id: standard_1
              type: standard
              sequence-numbers:
                - seq: 1
                  action: permit
                  number: "1:2"
                - seq: 2
                  action: deny
                  number:  "3:4"
            - id: 1
              sequence-numbers:
                - seq: 2
                  action: deny
                  number:  "3:4"
            - id: exp_test1
              type: expanded
              sequence-numbers:
                - seq: 3
                  action: permit
                  number: "5:6"
            - id: exp_test2
              type: expanded
              sequence-numbers:
                - seq: 3
                  action: permit
                  number: "5:6"
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# bgp community-list 1 seq 2 deny 3:4
# bgp community-list expanded exp_test1 seq 3 permit 5:6
# bgp community-list expanded exp_test2 seq 3 permit 5:6
# bgp community-list standard standard_1 seq 1 permit 1:2
# bgp community-list standard standard_1 seq 2 deny 3:4
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config bgp
# !
# bgp community-list 1 seq 2 deny 3:4
# bgp community-list expanded exp_test1 seq 3 permit 5:6
# bgp community-list expanded exp_test2 seq 3 permit 5:6
# bgp community-list standard standard_1 seq 1 permit 1:2
# bgp community-list standard standard_1 seq 2 deny 3:4
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete BGP Community Configuration
      celestica.sonic.bgp_community:
        config:
          community-list:
            - id: standard_1
              type: standard
              sequence-numbers:
                - seq: 1
                  action: permit
                  number: "1:2"
            - id: 1
              sequence-numbers:
                - seq: 2
                  action: deny
                  number:  "3:4"
            - id: exp_test1
              type: expanded
              sequence-numbers:
                - seq: 3
                  action: permit
                  number: "5:6"
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# bgp community-list expanded exp_test2 seq 3 permit 5:6
# bgp community-list standard standard_1 seq 2 deny 3:4
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.bgp_community.bgp_community import Bgp_communityArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.bgp_community.bgp_community import Bgp_community


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Bgp_communityArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp_community(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
