#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for bgp_af
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: bgp_af
version_added: 1.0.0
short_description: Resource module to configure BGP address family.
description:
  - This module configures and manages BGP address family on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of BGP address family configurations.
    type: dict
    suboptions:
      # BGP neighbor config
      bgp:
        description:
          - BGP configuration
        type: list
        elements: dict
        suboptions:
          asn:
            description:
              - ASN number. Range is 1-4294967295.
            type: str
            required: true
          vrf:
            description:
              - VRF name, shall be prefixed with 'Vrf' pattern. Maximum of 15 characters.
            type: str
          view:
            description:
              - View name.
            type: str
          address-family:
            description:
              - BGP neighbor configuration
            type: list
            elements: dict
            suboptions:
              afi:
                description:
                  - Address family type
                type: str
                choices: [ipv4, ipv6, l2vpn]
                required: true
              safi:
                description:
                  - Subsequent address family type
                type: str
                choices: [unicast, evpn]
                required: true

              # Advertise configuration
              advertise:
                description:
                  - Advertise configuration.
                  - Applicable only when afi is l2vpn and safi is evpn.
                type: dict
                suboptions:
                  ipv4:
                    description:
                      - IPv4 address-family advertise configuration.
                    type: dict
                    suboptions:
                      unicast:
                        description:
                          - Enable IPv4 address-family unicast advertise.
                        type: bool
                      gateway-ip:
                        description:
                          - Enable advertise gateway IP overlay index.
                        type: bool
                      route-map:
                        description:
                          - Route map for filtering specific routes.
                        type: str
                  ipv6:
                    description:
                      - IPv6 address-family advertise configuration.
                    type: dict
                    suboptions:
                      unicast:
                        description:
                          - Enable IPv6 address-family unicast advertise.
                        type: bool
                      gateway-ip:
                        description:
                          - Enable advertise gateway IP overlay index.
                        type: bool
                      route-map:
                        description:
                          - Route map for filtering specific routes.
                        type: str

              advertise-all-vni:
                description:
                  - Specify all vnis to be advertised.
                  - Valid when afi is l2vpn only.
                type: bool

              # Aggregate address configuration
              aggregate:
                description:
                  - Aggregate entries.
                  - Valid when afi is either ipv4 or ipv6 only.
                type: list
                elements: dict
                suboptions:
                  address:
                    description:
                      - Aggregate address with prefix.
                    type: str
                    required: True
                  as-set:
                    description:
                      - Enable or disable option to generate AS path information
                    type: bool
                  origin:
                    description:
                      - Origin codes.
                      - egp and igp indicates remote EGP and local IGP respectively.
                    type: str
                    choices: [egp, igp, incomplete]
                  route-map:
                    description:
                      - Route map name to aggregate network.
                    type: str
                  summary-only:
                    description:
                      - Option to filter more specific routes from updates
                    type: bool

              # Dampening configuration
              dampening:
                description:
                  - Dampening configuration.
                type: dict
                suboptions:
                  half-life-time:
                    description:
                      - Half-life time for the penalty, Range is 1-45.
                    type: int
                  reuse-value:
                    description:
                      - Value to start reusing a route, Range is  1-20000.
                    type: int
                  suppress-value:
                    description:
                      - Value to start suppressing a route, Range is 1-20000.
                    type: int
                  suppress-stable-route:
                    description:
                      - Maximum duration to suppress a stable route, Range is 1-255.
                    type: int

              # Administrative distance configuration
              distance:
                description:
                  - Administrative distance of BGP routes.
                type: dict
                suboptions:
                  # BGP Metric configuration
                  bgp:
                    description:
                      - Administrative distance of BGP routes.
                    type: dict
                    suboptions:
                      ebgp:
                        description:
                          - Metric for Externel BGP routes, Range is 1-255.
                        type: int
                      ibgp:
                        description:
                          - Metric for Internal BGP routes, Range is 1-255.
                        type: int
                      local:
                        description:
                          - Metric for local BGP routes, Range is 1-255.
                        type: int

                  # Metric for redistributed routes
                  metric:
                    description:
                      - Metric for redistributed routes.
                    type: list
                    elements: dict
                    suboptions:
                      value:
                        description:
                          - Metric value for network prefix, Range is 1-255.
                        type: int
                        required: True
                      prefix:
                        description:
                          - IPv4 address with prefix.
                        type: str
                        required: True

              # Maximum paths configuration
              max-path:
                description:
                  - Maximum paths configuration.
                type: dict
                suboptions:
                  ebgp:
                    description:
                      - Maximum paths in ebgp ECMP, range 1-128.
                    type: int
                  ibgp:
                    description:
                      - Maximum paths value for ECMP in EBGP for this BGP instance, range 1-128.
                    type: int
                  equal-cluster-length:
                    description:
                      - Option to enable or disable equal cluster length.
                      - Valid when ibgp is mentioned.
                    type: bool

              # Network configuration
              network:
                description:
                  - Network information to announce via BGP
                type: list
                elements: dict
                suboptions:
                  prefix:
                    description:
                      - Prefix address.
                    type: str
                    required: True
                  backdoor:
                    description:
                      - Option to specify a BGP backdoor route.
                    type: bool
                  route-map:
                    description:
                      - Route map name.
                    type: str

              # Redistribute configuration
              redistribute:
                description:
                  - Redistribute information from another routing protocol
                type: list
                elements: dict
                suboptions:
                  protocol:
                    description:
                      - Specifies the protocol for configuring redistribute information.
                    type: str
                    choices: [connected, kernel, ospf, static, table]
                    required: True
                  metric:
                    description:
                      - Metric for redistributed routes, Range is 0-4294967295.
                    type: int
                  route-map:
                    description:
                      - Route map name.
                    type: str
                  instance-id:
                    description:
                      - OSPF or Table instance identifier, Range is 1-65535.
                      - Applicable when protocol is either ospf or table only.
                    type: int

              # Table map configuration
              table-map:
                description:
                  - BGP table to RIB route download filter configuration.
                  - Route map name to be specified.
                type: str

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  bgp router-id 30.1.1.1
#  !
#  address-family ipv4 unicast
#   aggregate-address 40.1.1.0/24 as-set
#  exit-address-family
# exit
# !
# route-map testmap permit 2
# exit
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge BGP Address Family Configuration
      celestica.sonic.bgp_af:
        config:
          bgp:
            - asn: 1
              address-family:
                - afi: ipv4
                  safi: unicast
                  aggregate:
                    - address: 10.1.1.0/24
                    - address: 10.1.2.0/24
                      as-set: true
                  max-path:
                    ebgp: 30
                  network:
                    - prefix: 20.1.3.0/24
                    - prefix: 20.1.4.0/24
                      backdoor: true
                  redistribute:
                    - protocol: static
                      metric: 2
                      route-map: testmap
                    - protocol: table
                      metric: 3
                      route-map: testmap
                      instance-id: 1
                  table-map: t1
                - afi: l2vpn
                  safi: evpn
                  advertise-all-vni: true
            - asn: 1
              vrf: Vrf1
              address-family:
                - afi: ipv6
                  safi: unicast
                  aggregate:
                    - address: 11::/64
                      origin: igp
                    - address: 33::/64
                      route-map: testmap
                  max-path:
                    ibgp: 3
                    equal-cluster-length: true
                  network:
                    - prefix: 55::/64
                    - prefix: 77::/64
                      route-map: testmap
                  redistribute:
                    - protocol: connected
                    - protocol: kernel
                      metric: 33
                  table-map: t2
            - asn: 1
              view: view2
              address-family:
                - afi: ipv4
                  safi: unicast
                  aggregate:
                    - address: 10.1.3.0/24
                      summary-only: true
                  max-path:
                    ebgp: 30
                    ibgp: 3
                  network:
                    - prefix: 20.1.2.0/24
                  redistribute:
                    - protocol: ospf
                      metric: 4
                      route-map: testmap
                      instance-id: 2
                    - protocol: table
                      metric: 5
                      route-map: testmap
                    - protocol: ospf
                      metric: 6
                      route-map: testmap
                  table-map: t3
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  bgp router-id 30.1.1.1
#  !
#  address-family ipv4 unicast
#   network 20.1.3.0/24
#   network 20.1.4.0/24 backdoor
#   aggregate-address 10.1.1.0/24
#   aggregate-address 10.1.2.0/24 as-set
#   aggregate-address 40.1.1.0/24 as-set
#   redistribute static metric 2 route-map testmap
#   redistribute table 1 metric 3 route-map testmap
#   maximum-paths 30
#   table-map t1
#  exit-address-family
#  !
#  address-family l2vpn evpn
#   advertise-all-vni
#  exit-address-family
# exit
# !
# router bgp 1 vrf Vrf1
#  !
#  address-family ipv6 unicast
#   network 55::/64
#   network 77::/64 route-map testmap
#   aggregate-address 11::/64 origin igp
#   aggregate-address 33::/64 route-map testmap
#   redistribute kernel metric 33
#   redistribute connected
#   maximum-paths ibgp 3 equal-cluster-length
#   table-map t2
#  exit-address-family
# exit
# !
# router bgp 1 view view2
#  !
#  address-family ipv4 unicast
#   network 20.1.2.0/24
#   aggregate-address 10.1.3.0/24 summary-only
#   redistribute ospf 2 metric 4 route-map testmap
#   redistribute ospf metric 6 route-map testmap
#   redistribute table metric 5 route-map testmap
#   maximum-paths 30
#   maximum-paths ibgp 3
#   table-map t3
#  exit-address-family
# exit
# !
# route-map testmap permit 2
# exit
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  bgp router-id 30.1.1.1
#  !
#  address-family ipv4 unicast
#   network 20.1.3.0/24
#   network 20.1.4.0/24 backdoor
#   aggregate-address 10.1.1.0/24
#   aggregate-address 10.1.2.0/24 as-set
#   aggregate-address 40.1.1.0/24 as-set
#   redistribute static metric 2 route-map testmap
#   redistribute table 1 metric 3 route-map testmap
#   maximum-paths 30
#   table-map t1
#  exit-address-family
#  !
#  address-family l2vpn evpn
#   advertise-all-vni
#  exit-address-family
# exit
# !
# router bgp 1 vrf Vrf1
#  !
#  address-family ipv6 unicast
#   network 55::/64
#   network 77::/64 route-map testmap
#   aggregate-address 11::/64 origin igp
#   aggregate-address 33::/64 route-map testmap
#   redistribute kernel metric 33
#   redistribute connected
#   maximum-paths ibgp 3 equal-cluster-length
#   table-map t2
#  exit-address-family
# exit
# !
# router bgp 1 view view2
#  !
#  address-family ipv4 unicast
#   network 20.1.2.0/24
#   aggregate-address 10.1.3.0/24 summary-only
#   redistribute ospf 2 metric 4 route-map testmap
#   redistribute ospf metric 6 route-map testmap
#   redistribute table metric 5 route-map testmap
#   maximum-paths 30
#   maximum-paths ibgp 3
#   table-map t3
#  exit-address-family
# exit
# !
# route-map testmap permit 2
# exit
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete BGP Address Family Configuration
      celestica.sonic.bgp_af:
        config:
          bgp:
            - asn: 1
              address-family:
                - afi: ipv4
                  safi: unicast
                  aggregate:
                    - address: 10.1.1.0/24
                  max-path:
                    ebgp: 30
                  network:
                    - prefix: 20.1.4.0/24
                      backdoor: true
                  redistribute:
                    - protocol: static
                      metric: 2
                      route-map: testmap
                  table-map: t1
                - afi: l2vpn
                  safi: evpn
                  advertise-all-vni: true
            - asn: 1
              vrf: Vrf1
              address-family:
                - afi: ipv6
                  safi: unicast
                  aggregate:
                    - address: 33::/64
                      route-map: testmap
                  network:
                    - prefix: 55::/64
                  redistribute:
                    - protocol: kernel
                      metric: 33
            - asn: 1
              view: view2
        state: deleted


# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# router bgp 1
#  bgp router-id 30.1.1.1
#  !
#  address-family ipv4 unicast
#   network 20.1.3.0/24
#   aggregate-address 10.1.2.0/24 as-set
#   aggregate-address 40.1.1.0/24 as-set
#   redistribute table 1 metric 3 route-map testmap
#  exit-address-family
# exit
# !
# router bgp 1 vrf Vrf1
#  !
#  address-family ipv6 unicast
#   network 77::/64 route-map testmap
#   aggregate-address 11::/64 origin igp
#   redistribute connected
#   maximum-paths ibgp 3 equal-cluster-length
#   table-map t2
#  exit-address-family
# exit
# !
# route-map testmap permit 2
# exit
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.bgp_af.bgp_af import Bgp_afArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.bgp_af.bgp_af import Bgp_af


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Bgp_afArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp_af(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
