#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for crm
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: crm
version_added: 1.0.0
short_description: Resource module to configure CRM.
description:
  - This module configures and manages CRM (Critical Resource Monitoring) on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - Specifies CRM configurations.
    type: dict
    suboptions:
      # CRM global config
      global:
        description:
          - Global CRM configurations.
        type: dict
        suboptions:
          polling-interval:
            description:
              - Configure CRM polling-interval in seconds.
            type: int

      # CRM resource configurations.
      resource:
        description:
          - Resource configurations.
          - List of resources are static, hence use delete with the resource name to configure default values.
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Name of the resource to be managed.
            type: str
            choices: [acl_group, acl_group_counter, acl_group_entry, acl_group_table, fdb, ipv4_neighbor, ipv4_nexthop, ipv4_route, ipv6_neighbor, ipv6_nexthop, ipv6_route, nexthop_group_member, nexthop_group_object]
            required: true
          threshold-type:
            description:
              - Configure threshold type.
            type: str
            choices: [percentage, used, free]
          high-threshold:
            description:
              - Configure threshold higher limit value.
            type: int
          low-threshold:
            description:
              - Configure threshold lower limit value.
            type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show crm summary
# Polling Interval:300 second(s)
# Celestica-DS1000# show crm threshold
# Resource Name             Threshold type  Low-threshold High-threshold
# -------------------------------------------------------------------------------------------------
# acl_group                 percentage      70              85
# acl_group_counter         percentage      70              85
# acl_group_entry           percentage      70              85
# acl_group_table           percentage      70              85
# fdb                       percentage      70              85
# ipv4_neighbor             percentage      70              85
# ipv4_nexthop              percentage      70              85
# ipv4_route                percentage      70              85
# ipv6_neighbor             percentage      70              85
# ipv6_nexthop              percentage      70              85
# ipv6_route                percentage      70              85
# nexthop_group_member      percentage      70              85
# nexthop_group_object      percentage      70              85
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge CRM Configuration
      celestica.sonic.crm:
        config:
          global:
            polling-interval: 30
          resource:
            - name: acl_group
              threshold-type: free
              high-threshold: 200
              low-threshold: 20
            - name: ipv4_neighbor
              high-threshold: 90
              low-threshold: 20
            - name: ipv6_neighbor
              threshold-type: used
              high-threshold: 120
              low-threshold: 10
            - name: fdb
              high-threshold: 90
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show crm summary
# Polling Interval:30 second(s)
# Celestica-DS1000# show crm threshold
# Resource Name             Threshold type  Low-threshold High-threshold
# -------------------------------------------------------------------------------------------------
# acl_group                 free            20              200
# acl_group_counter         percentage      70              85
# acl_group_entry           percentage      70              85
# acl_group_table           percentage      70              85
# fdb                       percentage      70              90
# ipv4_neighbor             percentage      20              90
# ipv4_nexthop              percentage      70              85
# ipv4_route                percentage      70              85
# ipv6_neighbor             used            10              120
# ipv6_nexthop              percentage      70              85
# ipv6_route                percentage      70              85
# nexthop_group_member      percentage      70              85
# nexthop_group_object      percentage      70              85
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show crm summary
# Polling Interval:30 second(s)
# Celestica-DS1000# show crm threshold
# Resource Name             Threshold type  Low-threshold High-threshold
# -------------------------------------------------------------------------------------------------
# acl_group                 free            20              200
# acl_group_counter         percentage      70              85
# acl_group_entry           percentage      70              85
# acl_group_table           percentage      70              85
# fdb                       percentage      70              90
# ipv4_neighbor             percentage      20              90
# ipv4_nexthop              percentage      70              85
# ipv4_route                percentage      70              85
# ipv6_neighbor             used            10              120
# ipv6_nexthop              percentage      70              85
# ipv6_route                percentage      70              85
# nexthop_group_member      percentage      70              85
# nexthop_group_object      percentage      70              85
# Celestica-DS1000#
#
#
# Play:
# ----
#
    - name: Delete CRM Configuration
      celestica.sonic.crm:
        config:
          global:
            polling-interval: 30
          resource:
            - name: acl_group
            - name: ipv4_neighbor
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show crm summary
# Polling Interval:300 second(s)
# Celestica-DS1000# show crm threshold
# Resource Name             Threshold type  Low-threshold High-threshold
# -------------------------------------------------------------------------------------------------
# acl_group                 percentage      70              85
# acl_group_counter         percentage      70              85
# acl_group_entry           percentage      70              85
# acl_group_table           percentage      70              85
# fdb                       percentage      70              90
# ipv4_neighbor             percentage      70              85
# ipv4_nexthop              percentage      70              85
# ipv4_route                percentage      70              85
# ipv6_neighbor             used            10              120
# ipv6_nexthop              percentage      70              85
# ipv6_route                percentage      70              85
# nexthop_group_member      percentage      70              85
# nexthop_group_object      percentage      70              85
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.crm.crm import CrmArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.crm.crm import Crm


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=CrmArgs.argument_spec,
                           supports_check_mode=True)

    result = Crm(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
