#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for dot1x
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: dot1x
version_added: '1.0.0'
short_description: Resource module to configure Dot1x.
description:
  - This module configures and manages Dot1x on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of Dot1x configurations.
    type: dict
    suboptions:
      # Dot1x radius configuration
      radius:
        description:
          - Dot1x RADIUS configuration.
        type: dict
        suboptions:
          # RADIUS server config for Dot1x
          server:
            description:
              - RADIUS server configurations for Dot1x.
            type: list
            elements: dict
            suboptions:
              type:
                description:
                  - RADIUS server type for Dot1x authentication.
                  - One server in each primary and secondary are allowed.
                type: str
                choices: [primary, secondary]
                required: true
              ip-addr:
                description:
                  - IPv4 address of server.
                type: str
              port:
                description:
                  - Port number of the server, Range is 1-65535.
                type: int
              encrypted-passkey:
                description:
                  - Encrypted passkey of the RADIUS server.
                type: str
              vrf:
                description:
                  - VRF name, shall be prefixed with 'Vrf' pattern.
                type: str

          # RADIUS vsa to vlan mapping config
          vsa-vlan:
            description:
              - RADIUS VSA(Vendor Specific Attribute) to VLAN identifier mapping configurations for Dot1x.
            type: list
            elements: dict
            suboptions:
              vsa-description:
                description:
                  - VSA description. Maximum of 4-63 characters.
                type: str
                required: true
              vlan:
                description:
                  - VLAN identifier. Range is 1-4094.
                type: int

      # Dot1x configurations in interfaces
      interface:
        description:
          - Dot1x configurations in interfaces
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, ie, Ethernet0.
              - Only Ethernet interfaces are allowed.
            type: str
            required: true
          auth-mode:
            description:
              - Dot1x authentication mode.
            type: str
            choices: [multi-host, single-host]
          enable:
            description:
              - Enable or disable Dot1x on interface level.
            type: bool
          mab-backoff-timer:
            description:
              - Dot1x MAB backoff timer in seconds, Range is 0-360.
            type: int
          mab-enable:
            description:
              - Enable or disable MAB on interface level.
            type: bool
          max-clients:
            description:
              - Maximum clients allowed on interface level, Range is 1-16.
            type: int
          reauth-timer:
            description:
              - Reauthentication timer in seconds on interface level, Range is 0-7200.
            type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - replaced
      - overridden
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config dot1x
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge Dot1x Configuration
      celestica.sonic.dot1x:
        config:
          radius:
            server:
              - type: primary
                ip-addr: 1.1.1.1
                port: 101
                encrypted-passkey: key1
                vrf: Vrf1
              - type: secondary
                ip-addr: 2.2.2.2
                port: 201
                encrypted-passkey: key2
            vsa-vlan:
              - vsa-description: test_vsa1
                vlan: 301
              - vsa-description: test_vsa2
                vlan: 302
          interface:
            - name: Ethernet0
              auth-mode: single-host
              mab-backoff-timer: 100
              max-clients: 12
              reauth-timer: 200
            - name: Ethernet1
              enable: true
              mab-enable: true
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config dot1x
# !
# dot1x radius vsa-vlan test_vsa1 301
# dot1x radius vsa-vlan test_vsa2 302
# !
# dot1x radius server primary 1.1.1.1 101 key1 Vrf1 encrypted
# dot1x radius server secondary 2.2.2.2 201 key2 encrypted
# !
# interface Ethernet 0
#  dot1x reauth-timer 200
#  dot1x auth-mode single-host
#  dot1x max-clients 12
#  dot1x mab backoff-timer 100
# !
# interface Ethernet 1
#  dot1x enable
#  dot1x mab enable
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config dot1x
# !
# dot1x radius vsa-vlan test_vsa1 301
# dot1x radius vsa-vlan test_vsa2 302
# !
# dot1x radius server primary 1.1.1.1 101 key1 Vrf1 encrypted
# dot1x radius server secondary 2.2.2.2 201 key2 encrypted
# !
# interface Ethernet 0
#  dot1x reauth-timer 200
#  dot1x auth-mode single-host
#  dot1x max-clients 12
#  dot1x mab backoff-timer 100
# !
# interface Ethernet 1
#  dot1x enable
#  dot1x mab enable
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete Dot1x Configuration
      celestica.sonic.dot1x:
        config:
          radius:
            server:
              - type: secondary
            vsa-vlan:
              - vsa-description: test_vsa1
          interface:
            - name: Ethernet0
              auth-mode: single-host
              mab-backoff-timer: 100
              max-clients: 12
              reauth-timer: 200
            - name: Ethernet1
              enable: true
              mab-enable: true
        state: deleted
#
# After state:
# ------------
#
# Celestica-DS1000# show running-config dot1x
# !
# dot1x radius vsa-vlan test_vsa2 302
# !
# dot1x radius server primary 1.1.1.1 101 key1 Vrf1 encrypted
# !
# interface Ethernet 0
# !
# interface Ethernet 1
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.dot1x.dot1x import Dot1xArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.dot1x.dot1x import Dot1x


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Dot1xArgs.argument_spec,
                           supports_check_mode=True)

    result = Dot1x(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
