#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for edge_security
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: edge_security
version_added: '1.0.0'
short_description: Resource module to configure edge security feature.
description:
  - This module configures and manages edge security feature on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of edge security configurations.
    type: dict
    suboptions:
      # Edge security configurations in interfaces
      interface:
        description:
          - Edge security configurations in interfaces
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, ie, Ethernet0.
              - Only Ethernet interfaces are allowed.
            type: str
            required: true
          enable:
            description:
              - Enable or disable edge security on interface level.
            type: bool
          dynamic-learn-max:
            description:
              - Limit for dynamic MAC learn on interface level,Range is 0-16.
            type: int
          sticky-mac:
            description:
              - Sticky MAC configuration.
              - MAC address formats nn:nn:nn:nn:nn:nn, nn-nn-nn-nn-nn-nn and nnnn.nnnn.nnnn are allowed.
            type: str
          violation-action:
            description:
              - Violation action configuration.
            type: str
            choices: [restrict, shutdown]

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config edge-security
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge Edge Security Configuration
      celestica.sonic.edge_security:
        config:
          interface:
            - name: Ethernet0
              enable: true
              dynamic-learn-max: 10
              sticky-mac: 00:b0:d0:63:c2:26
              violation-action: shutdown
            - name: Ethernet1
              enable: true
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config edge-security
# !
# interface Ethernet 0
#  edge-security dynamic-learn-max 10
#  edge-security violation-action shutdown
#  edge-security enable
#  edge-security sticky-mac 00:b0:d0:63:c2:26
# !
# interface Ethernet 1
#  edge-security enable
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config edge-security
# !
# interface Ethernet 0
#  edge-security dynamic-learn-max 10
#  edge-security violation-action shutdown
#  edge-security enable
#  edge-security sticky-mac 00:b0:d0:63:c2:26
# !
# interface Ethernet 1
#  edge-security enable
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete Edge Security Configuration
      celestica.sonic.edge_security:
        config:
          interface:
            - name: Ethernet0
              dynamic-learn-max: 10
              sticky-mac: 00:b0:d0:63:c2:26
              violation-action: shutdown
            - name: Ethernet1
              enable: true
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config edge-security
# !
# interface Ethernet 0
#  edge-security enable
# !
# interface Ethernet 1
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.edge_security.edge_security import Edge_securityArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.edge_security.edge_security import Edge_security


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Edge_securityArgs.argument_spec,
                           supports_check_mode=True)

    result = Edge_security(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
