#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for interface
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: interface
version_added: 1.0.0
short_description: Resource module to configure Ethernet interface.
description:
  - This module configures and manages Ethernet interface on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of Ethernet interface configurations.
      - Ethernet interfaces cannot be deleted, hence delete all and delete with name are ignored.
    type: dict
    suboptions:
      # Ethernet Interface config
      interface:
        description:
          - Interface configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. Ethernet0.
            type: str
            required: true
          enabled:
            description:
              - Admin state of the interface
            type: bool
          advertise-speed:
            description:
              - Advertised interface speed
            type: str
          advertise-type:
            description:
              - Advertised interface type
            type: str
          channel-group:
            description:
              - PortChannel group identifier. Range is 1-256.
            type: int
          description:
            description:
              - Description of the interface
            type: str
          fec:
            description:
              - FEC configuration of the interface
            type: str
            choices: [FC, RS, none]
          mtu:
            description:
              - MTU configuration
              - Range is 1312-9216
            type: int
          speed:
            description:
              - Configured interface speed
              - auto is allowed to enable auto negotiation
            type: str
          tpid:
            description:
              - TPID configuration of the interface
            type: str
            choices: ["0x8100", "0x88a8", "0x9100", "0x9200"]
          type:
            description:
              - Configured media type on a interface
            type: str

          # Storm control configurations
          storm-control:
            description:
              - Storm control configurations on this interface.
            type: list
            elements: dict
            suboptions:
              type:
                description:
                  - BUM traffic storm type.
                type: str
                choices: [broadcast, unknown-multicast, unknown-unicast]
              rate:
                description:
                  - Storm rate in kbps, Range is 0-100000000.
                type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config interface Ethernet 10
# !
# interface Ethernet 10
#  fec none
#  mtu 9100
#  no shutdown
#  speed auto
# Celestica-DS1000# show running-config interface Ethernet 11
# !
# interface Ethernet 11
#  fec none
#  mtu 9100
#  no shutdown
#  speed auto
# Celestica-DS1000#
#
# Play:
# -----
#

    - name: Merge Interface Configuration
      celestica.sonic.interface:
        config:
          interface:
            - name: Ethernet10
              enabled: true
              advertise-speed: all
              advertise-type: CAUI4
              channel-group: 101
              description: "test_ethernet"
              fec: none
              speed: auto
              storm-control:
               - type: broadcast
                 rate: 25
               - type: unknown-multicast
                 rate: 26
            - name: Ethernet11
              enabled: false
              mtu: 1411
              tpid: "0x8100"
              type: SR4
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config interface Ethernet 10
# !
# interface Ethernet 10
#  description test_ethernet
#  fec none
#  mtu 9100
#  no shutdown
#  speed auto
#  advertise-type CAUI4
#  advertise-speed all
#  channel-group 101
#  storm-control type broadcast rate 25
#  storm-control type unknown-multicast rate 26
# Celestica-DS1000# show running-config interface Ethernet 11
# !
# interface Ethernet 11
#  fec none
#  mtu 1411
#  shutdown
#  speed auto
#  type SR4
#  tpid 0x8100
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config interface Ethernet 10
# !
# interface Ethernet 10
#  description test_ethernet
#  fec none
#  mtu 9100
#  no shutdown
#  speed auto
#  advertise-type CAUI4
#  advertise-speed all
#  channel-group 101
#  storm-control type broadcast rate 25
#  storm-control type unknown-multicast rate 26
# Celestica-DS1000# show running-config interface Ethernet 11
# !
# interface Ethernet 11
#  fec none
#  mtu 1411
#  shutdown
#  speed auto
#  type SR4
#  tpid 0x8100
# Celestica-DS1000#
#
# Play:
# -----
#

    - name: Delete Interface Configuration
      celestica.sonic.interface:
        config:
          interface:
            - name: Ethernet10
              enabled: true
              advertise-speed: all
              advertise-type: CAUI4
              channel-group: 101
              description: "test_ethernet"
              fec: none
              speed: auto
              storm-control:
               - type: broadcast
                 rate: 25
            - name: Ethernet11
              enabled: false
              mtu: 1411
              tpid: "0x8100"
              type: SR4
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config interface Ethernet 10
# !
# interface Ethernet 10
#  fec none
#  mtu 9100
#  shutdown
#  speed auto
#  advertise-type none
#  advertise-speed none
#  storm-control type unknown-multicast rate 26
# Celestica-DS1000# show running-config interface Ethernet 11
# !
# interface Ethernet 11
#  fec none
#  mtu 9100
#  no shutdown
#  speed auto
#  type none
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.interface.interface import InterfaceArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.interface.interface import Interface


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=InterfaceArgs.argument_spec,
                           supports_check_mode=True)

    result = Interface(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
