#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for l2_interface
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: l2_interface
version_added: 1.0.0
short_description: Resource module to configure Layer 2 interface.
description:
  - This module configures and manages Layer 2 interface on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of Layer 2 interface configurations.
    type: dict
    suboptions:
      # Layer 2 Interface config
      interface:
        description:
          - Layer 2 Interface configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. Ethernet0, PortChannel10, etc.
            type: str
            required: true
          # Access mode config
          access:
            type: dict
            description: Access mode configurations
            suboptions:
              vlan:
                type: int
                description: VLAN identifier in access mode. Range is 1-4094.
          # Trunk mode config
          trunk:
            description: Trunk mode configurations
            type: list
            elements: dict
            suboptions:
              vlan:
                description: VLAN identifier in trunk mode. Range is 1-4094.
                type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show vlan
# Flags:  d - Dynamic config done by system
#         c - User configuration
# ------------------------------------------------------------
# Name       Id         Members              Mode
# ------------------------------------------------------------
# Vlan101    101
# ------------------------------------------------------------
# Vlan102    102
# ------------------------------------------------------------
# Celestica-DS1000#
#
# Play:
# ----
#

    - name: Merge L2 Interface Configuration
      celestica.sonic.l2_interface:
        config:
          interface:
            - name: Ethernet0
              access:
                vlan: 101
              trunk:
                - vlan: 102
            - name: Ethernet1
              access:
                vlan: 102
            - name: PortChannel11
              access:
                vlan: 102
              trunk:
                - vlan: 101
        state: merged


# After state:
# ------------
#
# Celestica-DS1000# show vlan
# Flags:  d - Dynamic config done by system
#         c - User configuration
# ------------------------------------------------------------
# Name       Id         Members              Mode
# ------------------------------------------------------------
# Vlan101    101        Ethernet0 (c)        untagged
#                       PortChannel11 (c)    tagged
# ------------------------------------------------------------
# Vlan102    102        Ethernet0 (c)        tagged
#                       Ethernet1 (c)        untagged
#                       PortChannel11 (c)    untagged
# ------------------------------------------------------------
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show vlan
# Flags:  d - Dynamic config done by system
#         c - User configuration
# ------------------------------------------------------------
# Name       Id         Members              Mode
# ------------------------------------------------------------
# Vlan101    101        Ethernet0 (c)        untagged
#                       PortChannel11 (c)    tagged
# ------------------------------------------------------------
# Vlan102    102        Ethernet0 (c)        tagged
#                       Ethernet1 (c)        untagged
#                       PortChannel11 (c)    untagged
# ------------------------------------------------------------
# Celestica-DS1000#
#
#
# Play:
# ----
#
    - name: Delete L2 Interface Configuration
      celestica.sonic.l2_interface:
        config:
          interface:
            - name: Ethernet0
              trunk:
                - vlan: 102
            - name: Ethernet1
              access:
                vlan: 102
            - name: PortChannel11
              trunk:
                - vlan: 101
        state: deleted


# After state:
# ------------
#
# Celestica-DS1000# show vlan
# Flags:  d - Dynamic config done by system
#         c - User configuration
# ------------------------------------------------------------
# Name       Id         Members              Mode
# ------------------------------------------------------------
# Vlan101    101        Ethernet0 (c)        untagged
# ------------------------------------------------------------
# Vlan102    102        PortChannel11 (c)    untagged
# ------------------------------------------------------------
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.l2_interface.l2_interface import L2_interfaceArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.l2_interface.l2_interface import L2_interface


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=L2_interfaceArgs.argument_spec,
                           supports_check_mode=True)

    result = L2_interface(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
