#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for l3_interface
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: l3_interface
version_added: 1.0.0
short_description: Resource module to configure Layer 3 interface.
description:
  - This module configures and manages Layer 3 interface on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of Layer 3 interface configurations.
    type: dict
    suboptions:
      # Layer 3 Interface config
      interface:
        description:
          - Layer 3 Interface configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. Ethernet0, PortChannel10, etc.
            type: str
            required: true
          # IPv4 config
          ipv4:
            description:
              - IPv4 configurations for the Layer 3 interface.
            type: dict
            suboptions:
              addresses:
                description:
                  - List of IPv4 addresses.
                type: list
                elements: dict
                suboptions:
                  address:
                    description:
                      - IPv4 address in the format <ipv4 address>/<mask>
                        for example, 193.0.4.1/24.
                    type: str
                    required: true
          # IPv6 config
          ipv6:
            description:
              - IPv6 configurations for the Layer 3 interface.
            type: dict
            suboptions:
              addresses:
                description:
                  - List of IPv6 addresses.
                type: list
                elements: dict
                suboptions:
                  address:
                    description:
                      - IPv6 address in the format <ipv6 address>/<mask>
                        for example, 2002:db8:2202:2::2/64.
                    type: str
                    required: true
              link-local-only:
                description:
                  - Enable IPv6 link local address on interface.
                type: bool

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
# Celestica-DS1000# show running-config interface Ethernet 0
# !
# interface Ethernet 0
#  ip address 10.1.1.0/24
# Celestica-DS1000# show running-config interface Vlan 101
# !
# interface Vlan 101
# Celestica-DS1000# show running-config interface Loopback 0
# !
# interface Loopback 0
# Celestica-DS1000# show running-config interface PortChannel 101
# !
# interface PortChannel 102
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge L3 Interface Configuration
      celestica.sonic.l3_interface:
        config:
          interface:
            - name: Vlan101
              ipv4:
                addresses:
                  - address: 20.1.1.0/24
                  - address: 20.2.1.0/24
            - name: Ethernet0
              ipv4:
                addresses:
                  - address: 10.20.30.0/24
              ipv6:
                addresses:
                  - address: 2002:db8:2202:2::2/64
                link-local-only: true
            - name: Loopback0
              ipv4:
                addresses:
                  - address: 30.1.1.0/24
            - name: PortChannel101
              ipv4:
                addresses:
                  - address: 40.1.1.0/24
              ipv6:
                link-local-only: true
        state: merged

# After state:
# ------------
# Celestica-DS1000# show running-config interface Ethernet 0
# !
# interface Ethernet 0
#  ipv6 use-link-local-only
#  ip address 10.1.1.1/24
#  ip address 10.20.30.0/24
#  ipv6 address 2002:db8:2202:2::2/64
# Celestica-DS1000# show running-config interface PortChannel 101
# !
# interface PortChannel 101
#  ipv6 use-link-local-only
#  ip address 40.1.1.0/24
# Celestica-DS1000# show running-config interface Loopback 0
# !
# interface Loopback 0
#  ip address 30.1.1.0/24
# Celestica-DS1000# show running-config interface Vlan 101
# !
# interface Vlan 101
#  ip address 20.1.1.0/24
#  ip address 20.2.1.0/24
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config interface Ethernet 0
# !
# interface Ethernet 0
#  ipv6 use-link-local-only
#  ip address 10.1.1.1/24
#  ip address 10.20.30.0/24
#  ipv6 address 2002:db8:2202:2::2/64
# Celestica-DS1000# show running-config interface PortChannel 101
# !
# interface PortChannel 101
#  ipv6 use-link-local-only
#  ip address 40.1.1.0/24
# Celestica-DS1000# show running-config interface Loopback 0
# !
# interface Loopback 0
#  ip address 30.1.1.0/24
# Celestica-DS1000# show running-config interface Vlan 101
# !
# interface Vlan 101
#  ip address 20.1.1.0/24
#  ip address 20.2.1.0/24
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete L3 Interface Configuration
      celestica.sonic.l3_interface:
        config:
          interface:
            - name: Vlan101
              ipv4:
                addresses:
                  - address: 20.1.1.0/24
            - name: Ethernet0
              ipv4:
                addresses:
                  - address: 10.20.30.0/24
              ipv6:
                addresses:
                  - address: 2002:db8:2202:2::2/64
            - name: Loopback0
              ipv4:
                addresses:
                  - address: 30.1.1.0/24
            - name: PortChannel101
              ipv6:
                link-local-only: true
        state: deleted

# After state:
# ------------
# Celestica-DS1000# show running-config interface Ethernet 0
# !
# interface Ethernet 0
#  ipv6 use-link-local-only
#  ip address 10.1.1.1/24
# Celestica-DS1000# show running-config interface PortChannel 101
# !
# interface PortChannel 101
#  ip address 40.1.1.0/24
# Celestica-DS1000# show running-config interface Vlan 101
# !
# interface Vlan 101
#  ip address 20.2.1.0/24
# Celestica-DS1000# show running-config interface Loopback 0
# !
# interface Loopback 0
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.l3_interface.l3_interface import L3_interfaceArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.l3_interface.l3_interface import L3_interface


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=L3_interfaceArgs.argument_spec,
                           supports_check_mode=True)

    result = L3_interface(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
