#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for loopback
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: loopback
version_added: 1.0.0
short_description: Resource module to configure Loopback interface.
description:
  - This module configures and manages Loopback interface on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of Loopback interface configurations.
    type: dict
    suboptions:
      # Loopback Interface config
      interface:
        description:
          - Interface configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. Loopback10. Loopback ID Range is 0-16383.
            type: str
            required: true
          enabled:
            description:
              - Admin state of the interface
            type: bool
          description:
            description:
              - Description of the interface
            type: str

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config interface Loopback
# !
# interface Loopback 0
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge Loopback Configuration
      celestica.sonic.loopback:
        config:
          interface:
            - name: Loopback0
              enabled: false
            - name: Loopback1
              description: test_loopback
              enabled: true
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config interface Loopback
# !
# interface Loopback 0
#  shutdown
# !
# interface Loopback 1
#  description test_loopback
#  no shutdown
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config interface Loopback
# !
# interface Loopback 0
#  shutdown
# !
# interface Loopback 1
#  description test_loopback
#  no shutdown
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete Loopback Configuration
      celestica.sonic.loopback:
        config:
          interface:
            - name: Loopback0
            - name: Loopback1
              description: test_loopback
              enabled: true
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config interface Loopback
# !
# interface Loopback 1
#  shutdown
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.loopback.loopback import LoopbackArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.loopback.loopback import Loopback


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=LoopbackArgs.argument_spec,
                           supports_check_mode=True)

    result = Loopback(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
