#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for mclag
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: mclag
version_added: 1.0.0
short_description: Resource module to configure McLAG.
description:
  - This module configures and manages McLAG on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of McLAG configurations.
    type: dict
    suboptions:
      # McLAG domain config
      domain:
        description:
          - McLAG domain configuration
          - Allowed to configure ONE domain entry only in the device.
        type: list
        elements: dict
        suboptions:
          id:
            description:
              - Domain identifier. Range is 1-4095.
            type: int
            required: true
          keep-alive:
            description:
              - Keep alive configuration in seconds
              - Range is 1-60
            type: int
          peer-ip:
            description:
              - Peer IP address
            type: str
          peer-link:
            description:
              - Full name of the interface, i.e. Ethernet0, PortChannel10, etc.
            type: str
          session-timeout:
            description:
              - Session timeout configuration in seconds
              - Range is 3-3600
            type: int
          source-ip:
            description:
              - Source IP address
            type: str
          system-mac:
            description:
              - System MAC address
            type: str

      # McLAG config in PortChannel interface
      port-channel:
        description:
          - McLAG configuration in PortChannel interface
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. PortChannel10.
            type: str
            required: true
          domain:
            description:
              - McLAG domain identifier. Range is 1-4095.
            type: int

      # McLAG config in VLAN interface
      vlan:
        description:
          - McLAG configuration in VLAN interface
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. Vlan10.
            type: str
            required: true
          unique-ip:
            description:
              - Enable unique IP
            type: bool

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
# Celestica-DS1000# show running-config mclag
# Celestica-DS1000# show running-config interface PortChannel
# !
# interface PortChannel 12
# !
# interface PortChannel 13
# !
# interface PortChannel 101
#
# Play:
# ----
#
    - name: Merge MCLAG Configuration
      celestica.sonic.mclag:
        config:
          domain:
            - id: 1
              peer-ip: 1.1.1.1
              peer-link: PortChannel13
              source-ip: 10.1.1.1
              system-mac: 10:23:33:45:55:60
              keep-alive: 5
              session-timeout: 15
          port-channel:
            - name: PortChannel12
              domain: 1
            - name: PortChannel13
              domain: 1
          vlan:
            - name: Vlan101
              unique-ip: true
            - name: Vlan102
              unique-ip: true
        state: merged

# After state:
# ------------
# Celestica-DS1000# show running-config mclag
# !
# mclag domain 1
#  keepalive 5
#  peer-ip 1.1.1.1
#  peer-link PortChannel 101
#  session-timeout 15
#  source-ip 10.1.1.1
#  system-mac 10:23:33:45:55:60
# !
# interface Vlan 101
#  unique-ip enable
# !
# interface Vlan 102
#  unique-ip enable
# Celestica-DS1000#
# Celestica-DS1000# show running-config interface PortChannel
# !
# interface PortChannel 12
#  mclag 1
# !
# interface PortChannel 13
#  mclag 1
# !
# interface PortChannel 101
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config mclag
# !
# mclag domain 1
#  keepalive 5
#  peer-ip 1.1.1.1
#  peer-link PortChannel 101
#  session-timeout 15
#  source-ip 10.1.1.1
#  system-mac 10:23:33:45:55:60
# !
# interface Vlan 101
#  unique-ip enable
# !
# interface Vlan 102
#  unique-ip enable
# Celestica-DS1000#
# Celestica-DS1000# show running-config interface PortChannel
# !
# interface PortChannel 12
#  mclag 1
# !
# interface PortChannel 13
#  mclag 1
# !
# interface PortChannel 101
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete MCLAG Configuration.
      celestica.sonic.mclag:
        config:
          domain:
            - id: 1
              peer-link: PortChannel13
              source-ip: 10.1.1.1
          port-channel:
            - name: PortChannel12
              domain: 1
          vlan:
            - name: Vlan101
              unique-ip: true
        state: deleted

# After state:
# ------------
# Celestica-DS1000# show running-config mclag
# !
# mclag domain 1
#  keepalive 5
#  peer-ip 1.1.1.1
#  session-timeout 15
#  system-mac 10:23:33:45:55:60
# !
# interface Vlan 102
#  unique-ip enable
# Celestica-DS1000#
# Celestica-DS1000# show running-config interface PortChannel
# !
# interface PortChannel 12
# !
# interface PortChannel 13
#  mclag 1
# !
# interface PortChannel 101
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.mclag.mclag import MclagArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.mclag.mclag import Mclag


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=MclagArgs.argument_spec,
                           supports_check_mode=True)

    result = Mclag(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
