#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for mirror_session
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: mirror_session
version_added: 1.0.0
short_description: Resource module to configure mirror sessions.
description:
  - This module configures and manages mirror sessions on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - Specifies configurations.
    type: dict
    suboptions:
      # Mirror session config
      session:
        description:
          - Session configurations
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Session name. Maximum of 32 characters.
            type: str
            required: true

          # ERSPAN session config
          erspan:
            description:
              - ERSPAN session configurations.
              - ERSPAN sessions cannot be modified or deleted once created, hence remove the session entry to delete ERSPAN configurations.
            type: dict
            suboptions:
              destination-address:
                description:
                  - Destination IPv4 address.
                type: str
              source-address:
                description:
                  - Source IPv4 address.
                type: str
              dscp:
                description:
                  - DSCP value. Range is 0-63.
                type: int
              direction:
                description:
                  - Direction value.
                type: str
                choices: [rx, tx, both]
              ttl:
                description:
                  - TTL value. Range is 0-63.
                type: int
              gre:
                description:
                  - GRE value in hex(0x) format.
                type: str
              source-interface:
                description:
                  - Source interface name.
                  - Ethernet and PortChannel interfaces are allowed.
                type: str

          # SPAN session config
          span:
            description:
              - SPAN session configurations.
              - SPAN sessions cannot be deleted once created, hence remove the session entry to delete SPAN configurations.
            type: list
            elements: dict
            suboptions:
              destination-interface:
                description:
                  - Destination interface name.
                type: str
                required: true
              source-interface:
                description:
                  - Source interface name.
                  - Ethernet and PortChannel interfaces are allowed.
                type: str
              direction:
                description:
                  - Direction value.
                type: str
                choices: [rx, tx, both]

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config mirror-session
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge Mirror Session Configuration
      celestica.sonic.mirror_session:
        config:
          session:
            - name: test_erspan1
              erspan:
                destination-address: 10.1.1.1
                source-address: 20.1.1.1
                dscp: 2
                direction: rx
                ttl: 4
                gre: "0x65"
                source-interface: Ethernet0
            - name: test_span1
              span:
                - destination-interface: Ethernet2
                  source-interface: Ethernet1
                  direction: both
                - destination-interface: Ethernet2
                  source-interface: Ethernet3
                  direction: both
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config mirror-session
# !
# mirror-session test_erspan1
#  erspan dst-ip 10.1.1.1 src-ip 20.1.1.1 dscp 2 ttl 4 gre 0x65 source Ethernet 0 direction rx
# !
# mirror-session test_span1
#  span destination Ethernet 2 source Ethernet 1 direction both
#  span destination Ethernet 2 source Ethernet 3 direction both
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config mirror-session
# !
# mirror-session test_erspan1
#  erspan dst-ip 10.1.1.1 src-ip 20.1.1.1 dscp 2 ttl 4 gre 0x65 source Ethernet 0 direction rx
# !
# mirror-session test_span1
#  span destination Ethernet 2 source Ethernet 1 direction both
#  span destination Ethernet 2 source Ethernet 3 direction both
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete Mirror Session Configuration
      celestica.sonic.mirror_session:
        config:
          session:
            - name: test_span1
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config mirror-session
# !
# mirror-session test_erspan1
#  erspan dst-ip 10.1.1.1 src-ip 20.1.1.1 dscp 2 ttl 4 gre 0x65 source Ethernet 0 direction rx
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.mirror_session.mirror_session import Mirror_sessionArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.mirror_session.mirror_session import Mirror_session


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Mirror_sessionArgs.argument_spec,
                           supports_check_mode=True)

    result = Mirror_session(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
