#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for ntp
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: ntp
version_added: 1.0.0
short_description: Resource module to configure NTP.
description:
  - This module configures and manages NTP on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - Specifies configurations.
    type: dict
    suboptions:
      # NTP global config
      global:
        description:
          - Global configuration
        type: dict
        suboptions:
          source-interface:
            description:
              - Source interface configuration
            type: str
          vrf:
            description:
              - VRF configuration
            type: str
            choices:
              - default
              - mgmt

      # NTP server config
      server:
        description:
          - Server configuration
        type: list
        elements: dict
        suboptions:
          ip-addr:
            description:
              - IPv4 or IPv6 address of the server.
            type: str
            required: true

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config ntp
# Celestica-DS1000#
#
# Play:
# -----

    - name: Merge NTP Global Configuration
      celestica.sonic.ntp:
        config:
          global:
            source-interface: "Ethernet0"
            vrf: default
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config ntp
# !
# ntp source-interface Ethernet 0
# ntp vrf default
# Celestica-DS1000#


# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config ntp
# !
# ntp server 10.10.1.1
# Celestica-DS1000#
#
# Play:
# -----

    - name: Merge NTP Server Configuration
      celestica.sonic.ntp:
        config:
          server:
            - ip-addr: 10.10.1.2
            - ip-addr: 10.10.1.3
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config ntp
# !
# ntp server 10.10.1.1
# ntp server 10.10.1.2
# ntp server 10.10.1.3
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config ntp
# !
# ntp source-interface Ethernet 0
# ntp vrf default
# Celestica-DS1000#
#
# Play:
# -----

    - name: Delete NTP Global Configuration
      celestica.sonic.ntp:
        config:
          global:
            source-interface: "Ethernet0"
            vrf: default
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config ntp
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config ntp
# !
# ntp server 10.10.1.1
# ntp server 10.10.1.2
# ntp server 10.10.1.3
# Celestica-DS1000#
#
# Play:
# -----

    - name: Delete NTP Server Configuration
      celestica.sonic.ntp:
        config:
          server:
            - ip-addr: 10.10.1.2
            - ip-addr: 10.10.1.3
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config ntp
# !
# ntp server 10.10.1.1
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.ntp.ntp import NtpArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.ntp.ntp import Ntp


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=NtpArgs.argument_spec,
                           supports_check_mode=True)

    result = Ntp(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
