#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for prefix_list
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: prefix_list
version_added: 1.0.0
short_description: Resource module to configure prefix list.
description:
  - This module configures and manages prefix list on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of prefix list configurations.
    type: dict
    suboptions:
      # IPv4 prefix-list config
      ipv4:
        description:
          - IPv4 prefix list configuration
        type: dict
        suboptions:
          description:
            description:
              - Description of the IPv4 prefix list entry. Maximum of 100 characters.
            type: str
          prefix-list:
            description:
              - Prefix list configuration
            type: list
            elements: dict
            suboptions:
              name:
                description:
                  - Prefix list name
                type: str
                required: true
              # Sequence numbers under IPv4 prefix-list config
              sequence-numbers:
                description:
                  - Seqeuce number under prefix list configuration
                type: list
                elements: dict
                suboptions:
                  seq:
                    description:
                      - Sequence number. Range is 1-4294967295.
                    type: int
                    required: true
                  action:
                    description:
                      - Packet action.
                    type: str
                    choices: [deny, permit]
                    required: true
                  prefix:
                    description:
                      - IPv4 prefix with mask
                    type: str
                    required: true
                  ge:
                    description:
                      - Maximum prefix length to be matched. Range is 0-32.
                    type: int
                  le:
                    description:
                      - Minimum prefix length to be matched. Range is 0-32.
                    type: int

      # IPv6 prefix-list config
      ipv6:
        description:
          - IPv6 prefix list configuration
        type: dict
        suboptions:
          description:
            description:
              - Description of the IPv6 prefix list entry. Maximum of 100 characters.
            type: str
          prefix-list:
            description:
              - Prefix list configuration
            type: list
            elements: dict
            suboptions:
              name:
                description:
                  - Prefix list name
                type: str
                required: true
              # Sequence numbers under IPv6 prefix-list config
              sequence-numbers:
                description:
                  - Seqeuce number under prefix list configuration
                type: list
                elements: dict
                suboptions:
                  seq:
                    description:
                      - Sequence number. Range is 1-4294967295.
                    type: int
                    required: true
                  action:
                    description:
                      - Packet action.
                    type: str
                    choices: [deny, permit]
                  prefix:
                    description:
                      - IPv6 prefix with mask
                    type: str
                  ge:
                    description:
                      - Maximum prefix length to be matched. Range is 0-128.
                    type: int
                  le:
                    description:
                      - Minimum prefix length to be matched. Range is 0-128.
                    type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config
# !
# ip prefix-list ipv4_test2 seq 5 deny 10.1.1.0/24 le 24
# !
# ipv6 prefix-list ipv6_test1 seq 1 permit 1002:64:cf7::/64
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge Prefix List Configuration
      celestica.sonic.prefix_list:
        config:
          ipv4:
            description: ipv4_description
            prefix-list:
              - name: ipv4_test1
                sequence-numbers:
                  - seq: 1
                    action : permit
                    prefix : 1.1.1.0/24
                    le: 24
                  - seq: 2
                    action : deny
                    prefix : 2.2.2.0/24
          ipv6:
            description: ipv6_description
            prefix-list:
              - name: ipv6_test1
                sequence-numbers:
                  - seq: 3
                    action : permit
                    prefix : 2002:db8:2202:2::/64
              - name: ipv6_test2
                sequence-numbers:
                  - seq: 4
                    action : deny
                    prefix : 1002:dc7:2102:9::/64
                    le: 64
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config
# !
# ip prefix-list ipv4_test2 seq 5 deny 10.1.1.0/24 le 24
# ip prefix-list sequence-number description ipv4_description
# ip prefix-list ipv4_test1 seq 1 permit 1.1.1.0/24 le 24
# ip prefix-list ipv4_test1 seq 2 deny 2.2.2.0/24
# !
# ipv6 prefix-list ipv6_test1 seq 1 permit 1002:64:cf7::/64
# ipv6 prefix-list ipv6_test1 seq 3 permit 2002:db8:2202:2::/64
# ipv6 prefix-list sequence-number description ipv6_description
# ipv6 prefix-list ipv6_test2 seq 4 deny 1002:dc7:2102:9::/64 le 64
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config
# !
# ip prefix-list ipv4_test2 seq 5 deny 10.1.1.0/24 le 24
# ip prefix-list sequence-number description ipv4_description
# ip prefix-list ipv4_test1 seq 1 permit 1.1.1.0/24 le 24
# ip prefix-list ipv4_test1 seq 2 deny 2.2.2.0/24
# !
# ipv6 prefix-list ipv6_test1 seq 1 permit 1002:64:cf7::/64
# ipv6 prefix-list ipv6_test1 seq 3 permit 2002:db8:2202:2::/64
# ipv6 prefix-list sequence-number description ipv6_description
# ipv6 prefix-list ipv6_test2 seq 4 deny 1002:dc7:2102:9::/64 le 64
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete Prefix List Configuration
      celestica.sonic.prefix_list:
        config:
          ipv4:
            description: ipv4_description
            prefix-list:
              - name: ipv4_test1
                sequence-numbers:
                  - seq: 1
                    action : permit
                    prefix : 1.1.1.0/24
                    le: 24
          ipv6:
            prefix-list:
              - name: ipv6_test1
                sequence-numbers:
                  - seq: 3
                    action : permit
                    prefix : 2002:db8:2202:2::/64
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config bgp
# !
# ip prefix-list ipv4_test2 seq 5 deny 10.1.1.0/24 le 24
# ip prefix-list ipv4_test1 seq 2 deny 2.2.2.0/24
# !
# ipv6 prefix-list ipv6_test1 seq 1 permit 1002:64:cf7::/64
# ipv6 prefix-list sequence-number description ipv6_description
# ipv6 prefix-list ipv6_test2 seq 4 deny 1002:dc7:2102:9::/64 le 64
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.prefix_list.prefix_list import Prefix_listArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.prefix_list.prefix_list import Prefix_list


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Prefix_listArgs.argument_spec,
                           supports_check_mode=True)

    result = Prefix_list(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
