#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for router
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: router
version_added: 1.0.0
short_description: Resource module to configure static routes, router-id, next-hop tracking, protocol in default VRF.
description:
  - This module configures and manages static routes, router-id, next-hop tracking, protocol in default VRF on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of router configurations in default VRF.
    type: dict
    suboptions:
      # IPv4 router config in default VRF.
      ipv4:
        description:
          - IPv4 router configuration in default VRF.
        type: dict
        suboptions:
          # IPv4 router-id config in default VRF.
          router-id:
            description:
              - IPv4 address to use as router identifier.
            type: str

          # IPv4 next-hop tracking config in default VRF.
          next-hop-track:
            description:
              - IPv4 next-hop tracking configuration in default VRF.
            type: list
            elements: dict
            suboptions:
              protocol:
                description:
                  - Protocol name.
                type: str
                choices: [bgp, connected, kernel, ospf, resolve-via-default, static, table]
                required: true
              route-map:
                description:
                  - Route map name.
                type: str

          # IPv4 static route config in default VRF.
          route:
            description:
              - IPv4 static route configuration in default VRF.
            type: list
            elements: dict
            suboptions:
              destination:
                description:
                  - Destination prefix address with mask
                type: str
                required: true
              next-hops:
                description:
                  - Next hop configuration
                type: list
                elements: dict
                suboptions:
                  next-hop:
                    description:
                      - Next-hop router configuration
                      - IP address, interface name, blackhole, Null0 are allowed
                    type: str
                    required: true
                  interface:
                    description:
                      - IP gateway interface name
                    type: str
                  onlink:
                    description:
                      - Option to specify the nexthop as directly attached to the interface
                      - Valid only when interface is passed
                    type: bool
                  distance:
                    description:
                      - Distance value. Range is 1-255.
                    type: int
                  tag:
                    description:
                      - Tag value. Range is 1-4294967295.
                      - Valid only when distance is passed
                    type: int

          # IPv4 protocol config in default VRF.
          protocol:
            description:
              - IPv4 protocol configuration in default VRF.
              - Filter routing info exchanged between zebra and protocol.
            type: list
            elements: dict
            suboptions:
              name:
                description:
                  - Protocol name.
                type: str
                choices: [any, bgp, connected, kernel, ospf, static, table]
                required: true
              route-map:
                description:
                  - Route map name.
                type: str

      # IPv6 router config in default VRF.
      ipv6:
        description:
          - IPv6 router configuration in default VRF.
        type: dict
        suboptions:
          # IPv6 router-id config in default VRF.
          router-id:
            description:
              - IPv6 address to use as router identifier.
            type: str

          # IPv6 next-hop tracking config in default VRF.
          next-hop-track:
            description:
              - IPv6 next-hop tracking configuration in default VRF.
            type: list
            elements: dict
            suboptions:
              protocol:
                description:
                  - Protocol name.
                type: str
                choices: [bgp, connected, kernel, ospf, resolve-via-default, static, table]
                required: true
              route-map:
                description:
                  - Route map name.
                type: str

          # IPv6 static route config in default VRF.
          route:
            description:
              - IPv6 static route configuration in default VRF.
            type: list
            elements: dict
            suboptions:
              destination:
                description:
                  - Destination prefix address with mask
                type: str
                required: true
              next-hops:
                description:
                  - Next hop configuration
                type: list
                elements: dict
                suboptions:
                  next-hop:
                    description:
                      - Next-hop router configuration
                      - IP address, interface name, blackhole, Null0 are allowed
                    type: str
                    required: true
                  interface:
                    description:
                      - IP gateway interface name
                    type: str
                  onlink:
                    description:
                      - Option to specify the nexthop as directly attached to the interface
                      - Valid only when interface is passed
                    type: bool
                  distance:
                    description:
                      - Distance value. Range is 1-255.
                    type: int
                  tag:
                    description:
                      - Tag value.  Range is 1-4294967295.
                      - Valid only when distance is passed
                    type: int

          # IPv6 protocol config in default VRF.
          protocol:
            description:
              - IPv6 protocol configuration in default VRF.
              - Filter routing info exchanged between zebra and protocol.
            type: list
            elements: dict
            suboptions:
              name:
                description:
                  - Protocol name.
                type: str
                choices: [any, bgp, connected, kernel, ospf6, static, table]
                required: true
              route-map:
                description:
                  - Route map name.
                type: str

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge Static Route Configuration
      celestica.sonic.router:
        config:
          ipv4:
            router-id: 10.1.1.1
            next-hop-track:
              - protocol: static
                route-map: test_map1
              - protocol: kernel
                route-map: test_map2
            route:
              - destination: 20.1.1.0/24
                next-hops:
                  - next-hop: 10.10.1.1
                    interface: Ethernet0
                    onlink: true
                    distance: 23
                    tag: 233
                  - next-hop: Ethernet25
                    distance: 24
                    tag: 244
                  - next-hop: 10.30.2.1
                    distance: 5
                    tag: 55
              - destination: 40.1.1.0/24
                next-hops:
                  - next-hop: Null0
                    distance: 3
                    tag: 33
            protocol:
              - name: static
                route-map: test_map
          ipv6:
            next-hop-track:
              - protocol: static
                route-map: test_map1
              - protocol: kernel
                route-map: test_map2
            route:
              - destination: 1002:64:cf7::/64
                next-hops:
                  - next-hop: blackhole
                    distance: 4
                    tag: 44
              - destination: 2002:53:be2:30::/64
                next-hops:
                  - next-hop: 30::40
                    distance: 5
                    tag: 12
            protocol:
              - name: static
                route-map: test_map
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config
# !
# ip router-id 10.1.1.1
# ip route 20.1.1.0/24 10.30.2.1 tag 55 5
# ip route 20.1.1.0/24 10.10.1.1 Ethernet0 tag 233 23 onlink
# ip route 20.1.1.0/24 Ethernet25 tag 244 24
# ip route 40.1.1.0/24 Null0 tag 33 3
# ipv6 route 1002:64:cf7::/64 blackhole tag 44 4
# ipv6 route 2002:53:be2:30::/64 30::40 tag 12 5
# !
# ip nht kernel route-map test_map2
# !
# ipv6 nht kernel route-map test_map2
# !
# ip protocol static route-map test_map
# !
# ipv6 protocol static route-map test_map
# !
# ip nht static route-map test_map1
# !
# ipv6 nht static route-map test_map1
# !
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config
# !
# ip router-id 10.1.1.1
# ip route 20.1.1.0/24 10.30.2.1 tag 55 5
# ip route 20.1.1.0/24 10.10.1.1 Ethernet0 tag 233 23 onlink
# ip route 20.1.1.0/24 Ethernet25 tag 244 24
# ip route 40.1.1.0/24 Null0 tag 33 3
# ipv6 route 1002:64:cf7::/64 blackhole tag 44 4
# ipv6 route 2002:53:be2:30::/64 30::40 tag 12 5
# !
# ip nht kernel route-map test_map2
# !
# ipv6 nht kernel route-map test_map2
# !
# ip protocol static route-map test_map
# !
# ipv6 protocol static route-map test_map
# !
# ip nht static route-map test_map1
# !
# ipv6 nht static route-map test_map1
# !
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete Static Route Configuration
      celestica.sonic.router:
        config:
          ipv4:
            router-id: 10.1.1.1
            next-hop-track:
              - protocol: static
                route-map: test_map1
            route:
              - destination: 20.1.1.0/24
                next-hops:
                  - next-hop: 10.10.1.1
                    interface: Ethernet0
                    onlink: true
                    distance: 23
                    tag: 233
              - destination: 40.1.1.0/24
                next-hops:
                  - next-hop: Null0
                    distance: 3
                    tag: 33
            protocol:
              - name: static
                route-map: test_map
          ipv6:
            next-hop-track:
              - protocol: static
                route-map: test_map1
            route:
              - destination: 1002:64:cf7::/64
                next-hops:
                  - next-hop: blackhole
                    distance: 4
                    tag: 44
            protocol:
              - name: static
                route-map: test_map
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config
# !
# ip route 20.1.1.0/24 10.30.2.1 tag 55 5
# ip route 20.1.1.0/24 Ethernet25 tag 244 24
# ipv6 route 2002:53:be2:30::/64 30::40 tag 12 5
# !
# ip nht kernel route-map test_map2
# !
# ipv6 nht kernel route-map test_map2
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.router.router import RouterArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.router.router import Router


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=RouterArgs.argument_spec,
                           supports_check_mode=True)

    result = Router(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
