#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sflow
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: sflow
version_added: '1.0.0'
short_description: Resource module to configure sFlow.
description:
  - This module configures and manages sFlow on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of sFlow configurations.
    type: dict
    suboptions:
      # sFlow global config
      global:
        description:
          - Global sFlow configuration
        type: dict
        suboptions:
          agent:
            description:
              - Collector agent interface, Full name of the interface, ie, Ethernet0.
              - Ethernet, Loopback and VLAN interfaces are allowed.
            type: str
          enable:
            description:
              - Enable or disable sFlow globally.
            type: bool
          interface-disable-all:
            description:
              - Disable sFlow on all interfaces globally.
            type: bool
          polling-interval:
            description:
              - Collector polling interval, Range is 0-300, 0 is to disable.
            type: int

      # sFlow collector config
      collector:
        description:
          - Collector configurations
        type: list
        elements: dict
        suboptions:
          ip-addr:
            description:
              - IP address of collector, both IPv4 and IPv6 address are allowed.
            type: str
            required: true
          port:
            description:
              - Port number of the collector, Range is 1-65535.
            type: int
            required: true

      # sFlow configurations in interfaces
      interface:
        description:
          - sFlow configurations in interfaces
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, ie, Ethernet0.
              - Only Ethernet interfaces are allowed.
            type: str
            required: true
          enable:
            description:
              - Enable or disable sFlow on interface level.
            type: bool
          sampling-rate:
            description:
              - sFlow sampling rate, Range 256-8388608.
            type: int

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config sflow
# Celestica-DS1000# show running-config interface Ethernet 1
# !
# interface Ethernet 1
# Celestica-DS1000# show running-config interface Ethernet 2
# !
# interface Ethernet 2
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge sflow Configuration
      celestica.sonic.sflow:
        config:
          global:
            agent: Ethernet0
            enable: true
            interface-disable-all: true
            polling-interval: 25
          collector:
            - ip-addr: 1.1.1.1
              port: 6343
            - ip-addr: 1.1.1.2
              port: 6344
          interface:
            - name: Ethernet1
              enable: true
              sampling-rate: 257
            - name: Ethernet2
              enable: true
              sampling-rate: 258
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config sflow
# !
# sflow enable
# sflow agent-id Ethernet 0
# sflow polling-interval 25
# sflow interface disable all
# sflow collector 1.1.1.1 6343
# sflow collector 1.1.1.2 6344
# Celestica-DS1000# show running-config interface Ethernet 1
# !
# interface Ethernet 1
#  sflow enable
#  sflow sampling-rate 257
# Celestica-DS1000# show running-config interface Ethernet 2
# !
# interface Ethernet 2
#  sflow enable
#  sflow sampling-rate 258
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config sflow
# !
# sflow enable
# sflow agent-id Ethernet 0
# sflow polling-interval 25
# sflow interface disable all
# sflow collector 1.1.1.1 6343
# sflow collector 1.1.1.2 6344
# Celestica-DS1000# show running-config interface Ethernet 1
# !
# interface Ethernet 1
#  sflow enable
#  sflow sampling-rate 257
# Celestica-DS1000# show running-config interface Ethernet 2
# !
# interface Ethernet 2
#  sflow enable
#  sflow sampling-rate 258
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete sflow Configuration
      celestica.sonic.sflow:
        config:
          global:
            agent: Ethernet0
            interface-disable-all: true
            polling-interval: 25
          collector:
            - ip-addr: 1.1.1.1
              port: 6343
          interface:
            - name: Ethernet2
              enable: true
              sampling-rate: 258
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config sflow
# !
# sflow enable
# sflow collector 1.1.1.2 6344
# Celestica-DS1000# show running-config interface Ethernet 1
# !
# interface Ethernet 1
#  sflow enable
#  sflow sampling-rate 257
# Celestica-DS1000# show running-config interface Ethernet 2
# !
# interface Ethernet 2
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.sflow.sflow import SflowArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.sflow.sflow import Sflow


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=SflowArgs.argument_spec,
                           supports_check_mode=True)

    result = Sflow(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
