#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for tacacs
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: tacacs
version_added: 1.0.0
short_description: Resource module to configure TACACS.
description:
  - This module configures and manages TACACS on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of TACACS configurations.
    type: dict
    suboptions:
      # TACACS global config
      global:
        description:
          - Global configuration
        type: dict
        suboptions:
          auth-type:
            description:
              - Authentication type
            type: str
            choices:
              - pap
              - chap
              - login
          encrypted-passkey:
            description:
              - Passkey in encrypted format
            type: str
          timeout:
            description:
              - Server timeout in seconds
              - Range is 1-60
            type: str

      # TACACS server config
      server:
        description:
          - Server configuration
        type: list
        elements: dict
        suboptions:
          ip-addr:
            description:
              - IP address of server
            type: str
            required: true
          auth-type:
            description:
              - Authentication type
            type: str
            choices:
              - pap
              - chap
              - login
          encrypted-passkey:
            description:
              - Passkey in encrypted format
            type: str
          port:
            description:
              - Port number. Range is 1-65535.
            type: int
          priority:
            description:
              - Priority configuration
              - Range is 1-64
            type: int
          timeout:
            description:
              - Server timeout in seconds
              - Range is 1-60
            type: str
          vrf:
            description:
              - VRF configuraiton
            type: str
            choices:
              - mgmt

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config tacacs
# !
# tacacs-server authtype chap
# tacacs-server host 1.1.1.1 port 25 auth_type chap
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge TACACS Configuration
      celestica.sonic.tacacs:
        config:
          global:
            auth-type: login
            encrypted-passkey: password
            timeout: 25
          server:
            - ip-addr: 2.2.2.2
              port: 23
              auth-type: login
              encrypted-passkey: hostkey1
              priority: 2
              timeout: 2
              vrf: mgmt
            - ip-addr: 2001:db8:3333:4444:5555:6666:7777:8888
              port: 24
              auth-type: chap
              encrypted-passkey: hostkey2
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config tacacs
# !
# tacacs-server authtype login
# tacacs-server timeout 25
# tacacs-server encrypted-passkey password
# tacacs-server host 1.1.1.1 port 25 auth_type chap
# tacacs-server host 2.2.2.2 encrypted-passkey hostkey1 port 23 priority 2 timeout 2 auth_type login vrf mgmt
# tacacs-server host 2001:db8:3333:4444:5555:6666:7777:8888 encrypted-passkey hostkey2 port 24 auth_type chap
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
# Celestica-DS1000# show running-config tacacs
# !
# tacacs-server authtype login
# tacacs-server timeout 25
# tacacs-server encrypted-passkey password
# tacacs-server host 1.1.1.1 port 25 auth_type chap
# tacacs-server host 2.2.2.2 encrypted-passkey hostkey1 port 23 priority 2 timeout 2 auth_type login vrf mgmt
# tacacs-server host 2001:db8:3333:4444:5555:6666:7777:8888 encrypted-passkey hostkey2 port 24 auth_type chap
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete TACACS Configuration
      celestica.sonic.tacacs:
        config:
          global:
            auth-type: login
            timeout: 25
          server:
            - ip-addr: 1.1.1.1
            - ip-addr: 2001:db8:3333:4444:5555:6666:7777:8888
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config tacacs
# !
# tacacs-server encrypted-passkey password
# tacacs-server host 2.2.2.2 encrypted-passkey hostkey1 port 23 priority 2 timeout 2 auth_type login vrf mgmt
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.tacacs.tacacs import TacacsArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.tacacs.tacacs import Tacacs


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=TacacsArgs.argument_spec,
                           supports_check_mode=True)

    result = Tacacs(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
