#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for vrf
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: vrf
version_added: 1.0.0
short_description: Resource module to configure VRF.
description:
  - This module configures and manages VRF on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of VRF configurations.
    type: dict
    suboptions:
      # VRF config
      vrf:
        description:
          - VRF configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - VRF name, shall be prefixed with 'Vrf' pattern. Maximum of 15 characters.
            type: str
            required: true
          ipv4-router-id:
            description:
              - IPv4 Router address.
            type: str
          ipv6-router-id:
            description:
              - IPv6 Router address.
            type: str
          vni:
            description:
              - VNI identifier. Range is 1-16777215.
            type: int

      # VRF config in interface
      interface:
        description:
          - VRF configuration in interface
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. Ethernet0, PortChannel10, Vlan10, etc.
            type: str
            required: true
          vrf:
            description:
              - VRF name, shall be prefixed with 'Vrf' pattern. Maximum of 15 characters.
            type: str

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config
# !
# vrf Vrf1
#  vni 1
#  ip router-id 1.1.1.1
# exit-vrf
# Celestica-DS1000#
#
# Play:
# ----
#

    - name: Merge VRF Configuration
      celestica.sonic.vrf:
        config:
          vrf:
            - name: Vrf2
              ipv4-router-id: 10.1.1.1
              vni: 2
            - name: Vrf3
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show running-config
# !
# vrf Vrf1
#  ip router-id 1.1.1.1
# exit-vrf
# !
# vrf Vrf2
#  vni 2
#  ip router-id 10.1.1.1
# exit-vrf
# !
# vrf Vrf3
#  ip router-id 1.1.1.1
# exit-vrf
# Celestica-DS1000#


# Using state : merged
#
# Before state:
# -------------
#
# Celestica-DS1000# show vrf
# VRF    Interfaces
# -----  --------------
# Vrf1
# Vrf2
# Vrf3
# Celestica-DS1000#
#
# Play:
# ----
#

    - name: Merge VRF-Interface Configuration
      celestica.sonic.vrf:
        config:
          interface:
            - name: Ethernet12
              vrf: Vrf1
            - name: PortChannel10
              vrf: Vrf2
            - name: Loopback0
              vrf: Vrf1
            - name: Vlan101
              vrf: Vrf2
        state: merged

# After state:
# ------------
#
# Celestica-DS1000# show vrf
# VRF    Interfaces
# -----  -------------
# Vrf1   Ethernet12
#        Loopback0
# Vrf2   PortChannel10
#        Vlan101
# Vrf3
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config
# !
# vrf Vrf1
#  ip router-id 1.1.1.1
# exit-vrf
# !
# vrf Vrf2
#  vni 2
#  ip router-id 10.1.1.1
# exit-vrf
# !
# vrf Vrf3
#  ip router-id 1.1.1.1
# exit-vrf
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete VRF Configuration
      celestica.sonic.vrf:
        config:
          vrf:
            - name: Vrf2
              ipv4-router-id: 10.1.1.1
              vni : 2
            - name: Vrf3
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config
# !
# vrf Vrf1
#  ip router-id 1.1.1.1
# exit-vrf
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show vrf
# VRF    Interfaces
# -----  -------------
# Vrf1   Ethernet12
#        Loopback0
# Vrf2   PortChannel10
#        Vlan101
# Vrf3
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete VRF-Interface Configuration
      celestica.sonic.vrf:
        config:
          interface:
            - name: Ethernet12
              vrf: Vrf1
            - name: PortChannel10
              vrf: Vrf2
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show vrf
# VRF    Interfaces
# -----  ------------
# Vrf1   Loopback0
# Vrf2   Vlan101
# Vrf3
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.vrf.vrf import VrfArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.vrf.vrf import Vrf


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=VrfArgs.argument_spec,
                           supports_check_mode=True)

    result = Vrf(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
