#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for vxlan
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: vxlan
version_added: 1.0.0
short_description: Resource module to configure VxLAN interface.
description:
  - This module configures and manages VxLAN interface on devices running Celestica SONiC NOS.
author: Celestica SONiC Ansible Team (@dharmaraj-gurusamy)
notes:
  - Tested against Advanced Celestica SONiC, release 2.0.
  - This module works with connection C(network_cli).
options:
  config:
    description:
      - A dictionary of VxLAN interface configurations.
    type: dict
    suboptions:
      vxlan-profile:
        description:
          - Enable / disable VxLAN profile
        type: bool
      # VNI map config
      vni-map:
        description:
          - VNI map configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - MAP name
            type: str
            required: true
          vni-id:
            description:
              - VNI identifier. Range is 1-16777215.
            type: int

      # VxLAN Interface config
      interface:
        description:
          - Interface configuration
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - Full name of the interface, i.e. vtep10 (Prefixed by 'vtep' and ID range is 1-60).
            type: str
            required: true
          source-ip:
            description:
              - Source IPv4 address of the interface
            type: str
          vtep-mac:
            description:
              - VTEP MAC address of the interface
            type: str

          # VNI config
          vni:
            description:
              - VNI map configuration
            type: list
            elements: dict
            suboptions:
              vni-id:
                description:
                  - VNI identifier. Range is 1-16777215.
                type: int
                required: true
              vlan-id:
                description:
                  - VLAN identifier. Range is 1-4094.
                type: int
                required: true

  state:
    description:
      - The state of the configuration after module completion.
      - C(merged) - Merge specified configuration with on-device running configuration.
      - C(deleted) - Delete the specified on-device running configuration or applies the default value.
    type: str
    choices:
      - merged
      - deleted
    default: merged
"""
EXAMPLES = """
# Using state : merged
#
# Before state:
# -------------
# Celestica-DS1000# show running-config vxlan
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Merge VxLAN Configuration
      celestica.sonic.vxlan:
        config:
          interface:
            - name: vtep12
              source-ip: 1.1.1.1
              vtep-mac: 00:00:10:00:00:00
              vni:
                - vni-id: 1
                  vlan-id: 101
                - vni-id: 2
                  vlan-id: 101
                - vni-id: 2
                  vlan-id: 102
        state: merged

    - name: Merge VxLAN Global Configuration
      celestica.sonic.vxlan:
        config:
          vxlan-profile: true
          vni-map:
            - name: Vrf1
              vni-id: 1
            - name: Vrf2
              vni-id: 2
        state: merged

# After state:
# ------------
# Celestica-DS1000# show running-config vxlan
# !
# vxlan-profile enable
# !
# vxlan vni-map Vrf1 1
# vxlan vni-map Vrf2 2
# !
# interface vxlan vtep12
#  source-ip 1.1.1.1 vtep-mac 00:00:10:00:00:00
#  map vni 1 vlan 101
#  map vni 2 vlan 101
#  map vni 2 vlan 102
# Celestica-DS1000#


# Using state : deleted
#
# Before state:
# -------------
#
# Celestica-DS1000# show running-config vxlan
# !
# vxlan-profile enable
# !
# vxlan vni-map Vrf1 1
# vxlan vni-map Vrf2 2
# !
# interface vxlan vtep12
#  source-ip 1.1.1.1 vtep-mac 00:00:10:00:00:00
#  map vni 1 vlan 101
#  map vni 2 vlan 101
#  map vni 2 vlan 102
# Celestica-DS1000#
#
# Play:
# ----
#
    - name: Delete VxLAN Global Configuration
      celestica.sonic.vxlan:
        config:
          vxlan-profile: true
          vni-map:
            - name: Vrf1
              vni-id: 1
            - name: Vrf2
              vni-id: 2
        state: deleted

    - name: Delete VxLAN VNI-VLAN Configuration
      celestica.sonic.vxlan:
        config:
          interface:
            - name: vtep12
              vni:
                - vni-id: 1
                  vlan-id: 101
                - vni-id: 2
                  vlan-id: 101
                - vni-id: 2
                  vlan-id: 102
        state: deleted

    - name: Delete VxLAN Source-IP Configuration
      celestica.sonic.vxlan:
        config:
          interface:
            - name: vtep12
              source-ip: 1.1.1.1
              vtep-mac: 00:00:10:00:00:00
        state: deleted

# After state:
# ------------
#
# Celestica-DS1000# show running-config vxlan
# !
# vxlan vni-map Vrf1 0
# vxlan vni-map Vrf2 0
# !
# interface vxlan vtep12
# Celestica-DS1000#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.argspec.vxlan.vxlan import VxlanArgs
from ansible_collections.celestica.sonic.plugins.module_utils.network.sonic.config.vxlan.vxlan import Vxlan


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=VxlanArgs.argument_spec,
                           supports_check_mode=True)

    result = Vxlan(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
