#
# -*- coding: utf-8 -*-
# Copyright 2024 Celestica Inc. All Rights Reserved.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the l3_access_list module
"""


class L3_access_listArgs(object):  # pylint: disable=R0903
    """The arg spec for the l3_access_list module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'access-list-ipv4': {'elements': 'dict',
                                             'options': {'name': {'required': True,
                                                                  'type': 'str'},
                                                         'sequence-numbers': {'elements': 'dict',
                                                                              'options': {'action': {'choices': ['deny',
                                                                                                                 'permit'],
                                                                                                     'type': 'str'},
                                                                                          'prefix': {'type': 'str'},
                                                                                          'remark': {'type': 'str'},
                                                                                          'seq': {'required': True,
                                                                                                  'type': 'int'}},
                                                                              'type': 'list'}},
                                             'type': 'list'},
                        'access-list-ipv6': {'elements': 'dict',
                                             'options': {'name': {'required': True,
                                                                  'type': 'str'},
                                                         'sequence-numbers': {'elements': 'dict',
                                                                              'options': {'action': {'choices': ['deny',
                                                                                                                 'permit'],
                                                                                                     'type': 'str'},
                                                                                          'prefix': {'type': 'str'},
                                                                                          'remark': {'type': 'str'},
                                                                                          'seq': {'required': True,
                                                                                                  'type': 'int'}},
                                                                              'type': 'list'}},
                                             'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
